-- Authored pools for Ausiris demo (Thai given × surname from rocket-demo, plus nicknames / archetypes)
INSERT INTO public.custom_ausiris_demo_config (kind,code,payload,is_active,sort_order) VALUES
('given_name','nara','{"thai": "นารา", "romanized": "Nara", "gender": "f"}'::jsonb,true,1),
('given_name','pim','{"thai": "พิมพ์", "romanized": "Pim", "gender": "f"}'::jsonb,true,2),
('given_name','praew','{"thai": "แพรว", "romanized": "Praew", "gender": "f"}'::jsonb,true,3),
('given_name','ploy','{"thai": "พลอย", "romanized": "Ploy", "gender": "f"}'::jsonb,true,4),
('given_name','namwan','{"thai": "น้ำหวาน", "romanized": "Namwan", "gender": "f"}'::jsonb,true,5),
('given_name','fah','{"thai": "ฟ้า", "romanized": "Fah", "gender": "f"}'::jsonb,true,6),
('given_name','mint','{"thai": "มิ้นท์", "romanized": "Mint", "gender": "f"}'::jsonb,true,7),
('given_name','fern','{"thai": "เฟิร์น", "romanized": "Fern", "gender": "f"}'::jsonb,true,8),
('given_name','may','{"thai": "เมย์", "romanized": "May", "gender": "f"}'::jsonb,true,9),
('given_name','nicha','{"thai": "ณิชา", "romanized": "Nicha", "gender": "f"}'::jsonb,true,10),
('given_name','kanokwan','{"thai": "กนกวรรณ", "romanized": "Kanokwan", "gender": "f"}'::jsonb,true,11),
('given_name','siriporn','{"thai": "ศิริพร", "romanized": "Siriporn", "gender": "f"}'::jsonb,true,12),
('given_name','wanida','{"thai": "วนิดา", "romanized": "Wanida", "gender": "f"}'::jsonb,true,13),
('given_name','apinya','{"thai": "อภิญญา", "romanized": "Apinya", "gender": "f"}'::jsonb,true,14),
('given_name','chuthamat','{"thai": "จุฑามาศ", "romanized": "Chuthamat", "gender": "f"}'::jsonb,true,15),
('given_name','kanyarat','{"thai": "กัญญารัตน์", "romanized": "Kanyarat", "gender": "f"}'::jsonb,true,16),
('given_name','supaporn','{"thai": "สุภาพร", "romanized": "Supaporn", "gender": "f"}'::jsonb,true,17),
('given_name','oranong','{"thai": "อรอนงค์", "romanized": "Oranong", "gender": "f"}'::jsonb,true,18),
('given_name','patcharee','{"thai": "พัชรี", "romanized": "Patcharee", "gender": "f"}'::jsonb,true,19),
('given_name','ratchanok','{"thai": "รัชนก", "romanized": "Ratchanok", "gender": "f"}'::jsonb,true,20),
('given_name','thanyarat','{"thai": "ธัญรัตน์", "romanized": "Thanyarat", "gender": "f"}'::jsonb,true,21),
('given_name','warunee','{"thai": "วารุณี", "romanized": "Warunee", "gender": "f"}'::jsonb,true,22),
('given_name','jiraporn','{"thai": "จิราพร", "romanized": "Jiraporn", "gender": "f"}'::jsonb,true,23),
('given_name','nattaya','{"thai": "ณัฐยา", "romanized": "Nattaya", "gender": "f"}'::jsonb,true,24),
('given_name','panida','{"thai": "พนิดา", "romanized": "Panida", "gender": "f"}'::jsonb,true,25),
('given_name','siriwan','{"thai": "ศิริวรรณ", "romanized": "Siriwan", "gender": "f"}'::jsonb,true,26),
('given_name','anong','{"thai": "อนงค์", "romanized": "Anong", "gender": "f"}'::jsonb,true,27),
('given_name','busakorn','{"thai": "บุษกร", "romanized": "Busakorn", "gender": "f"}'::jsonb,true,28),
('given_name','chanida','{"thai": "ชนิดา", "romanized": "Chanida", "gender": "f"}'::jsonb,true,29),
('given_name','duangjai','{"thai": "ดวงใจ", "romanized": "Duangjai", "gender": "f"}'::jsonb,true,30),
('given_name','arisa','{"thai": "อริสา", "romanized": "Arisa", "gender": "f"}'::jsonb,true,31),
('given_name','benjawan','{"thai": "เบญจวรรณ", "romanized": "Benjawan", "gender": "f"}'::jsonb,true,32),
('given_name','chompoo','{"thai": "ชมพู่", "romanized": "Chompoo", "gender": "f"}'::jsonb,true,33),
('given_name','dao','{"thai": "ดาว", "romanized": "Dao", "gender": "f"}'::jsonb,true,34),
('given_name','fon','{"thai": "ฝน", "romanized": "Fon", "gender": "f"}'::jsonb,true,35),
('given_name','kamonchanok','{"thai": "กมลชนก", "romanized": "Kamonchanok", "gender": "f"}'::jsonb,true,36),
('given_name','pimchanok','{"thai": "พิมพ์ชนก", "romanized": "Pimchanok", "gender": "f"}'::jsonb,true,37),
('given_name','supawadee','{"thai": "สุภาวดี", "romanized": "Supawadee", "gender": "f"}'::jsonb,true,38),
('given_name','orawan','{"thai": "อรวรรณ", "romanized": "Orawan", "gender": "f"}'::jsonb,true,39),
('given_name','chayanit','{"thai": "ชญานิษฐ์", "romanized": "Chayanit", "gender": "f"}'::jsonb,true,40),
('given_name','thanaporn','{"thai": "ธนพร", "romanized": "Thanaporn", "gender": "f"}'::jsonb,true,41),
('given_name','wipada','{"thai": "วิภาดา", "romanized": "Wipada", "gender": "f"}'::jsonb,true,42),
('given_name','anucha','{"thai": "อนุชา", "romanized": "Anucha", "gender": "m"}'::jsonb,true,43),
('given_name','somchai','{"thai": "สมชาย", "romanized": "Somchai", "gender": "m"}'::jsonb,true,44),
('given_name','surachai','{"thai": "สุรชัย", "romanized": "Surachai", "gender": "m"}'::jsonb,true,45),
('given_name','pramote','{"thai": "ปราโมทย์", "romanized": "Pramote", "gender": "m"}'::jsonb,true,46),
('given_name','wichai','{"thai": "วิชัย", "romanized": "Wichai", "gender": "m"}'::jsonb,true,47),
('given_name','thanakorn','{"thai": "ธนากร", "romanized": "Thanakorn", "gender": "m"}'::jsonb,true,48),
('given_name','kittisak','{"thai": "กิตติศักดิ์", "romanized": "Kittisak", "gender": "m"}'::jsonb,true,49),
('given_name','nattapong','{"thai": "ณัฐพงศ์", "romanized": "Nattapong", "gender": "m"}'::jsonb,true,50),
('given_name','apichat','{"thai": "อภิชาติ", "romanized": "Apichat", "gender": "m"}'::jsonb,true,51),
('given_name','boonlert','{"thai": "บุญเลิศ", "romanized": "Boonlert", "gender": "m"}'::jsonb,true,52),
('given_name','chatchai','{"thai": "ฉัตรชัย", "romanized": "Chatchai", "gender": "m"}'::jsonb,true,53),
('given_name','danai','{"thai": "ดนัย", "romanized": "Danai", "gender": "m"}'::jsonb,true,54),
('given_name','ekkachai','{"thai": "เอกชัย", "romanized": "Ekkachai", "gender": "m"}'::jsonb,true,55),
('given_name','ittipol','{"thai": "อิทธิพล", "romanized": "Ittipol", "gender": "m"}'::jsonb,true,56),
('given_name','jakkrit','{"thai": "จักรฤทธิ์", "romanized": "Jakkrit", "gender": "m"}'::jsonb,true,57),
('given_name','kritsada','{"thai": "กฤษฎา", "romanized": "Kritsada", "gender": "m"}'::jsonb,true,58),
('given_name','manop','{"thai": "มานพ", "romanized": "Manop", "gender": "m"}'::jsonb,true,59),
('given_name','narong','{"thai": "ณรงค์", "romanized": "Narong", "gender": "m"}'::jsonb,true,60),
('given_name','phichai','{"thai": "พิชัย", "romanized": "Phichai", "gender": "m"}'::jsonb,true,61),
('given_name','sakchai','{"thai": "ศักดิ์ชัย", "romanized": "Sakchai", "gender": "m"}'::jsonb,true,62),
('given_name','thana','{"thai": "ธนา", "romanized": "Thana", "gender": "m"}'::jsonb,true,63),
('given_name','udom','{"thai": "อุดม", "romanized": "Udom", "gender": "m"}'::jsonb,true,64),
('given_name','vorawut','{"thai": "วรวุฒิ", "romanized": "Vorawut", "gender": "m"}'::jsonb,true,65),
('given_name','yuthana','{"thai": "ยุทธนา", "romanized": "Yuthana", "gender": "m"}'::jsonb,true,66),
('given_name','weerachai','{"thai": "วีรชัย", "romanized": "Weerachai", "gender": "m"}'::jsonb,true,67),
('given_name','anuwat','{"thai": "อนุวัฒน์", "romanized": "Anuwat", "gender": "m"}'::jsonb,true,68),
('given_name','peerapat','{"thai": "พีรพัฒน์", "romanized": "Peerapat", "gender": "m"}'::jsonb,true,69),
('given_name','tanawat','{"thai": "ธนวัฒน์", "romanized": "Tanawat", "gender": "m"}'::jsonb,true,70),
('given_name','napat','{"thai": "ณภัทร", "romanized": "Napat", "gender": "m"}'::jsonb,true,71),
('given_name','siwat','{"thai": "ศิวัต", "romanized": "Siwat", "gender": "m"}'::jsonb,true,72),
('given_name','kamon','{"thai": "กมล", "romanized": "Kamon", "gender": "u"}'::jsonb,true,73),
('given_name','isara','{"thai": "อิสรา", "romanized": "Isara", "gender": "u"}'::jsonb,true,74)
ON CONFLICT (kind,code) DO UPDATE SET payload=EXCLUDED.payload, updated_at=now();
INSERT INTO public.custom_ausiris_demo_config (kind,code,payload,is_active,sort_order) VALUES
('surname','sukkasem','{"thai": "สุขเกษม", "romanized": "Sukkasem"}'::jsonb,true,1),
('surname','chaisiri','{"thai": "ชัยศิริ", "romanized": "Chaisiri"}'::jsonb,true,2),
('surname','wongchai','{"thai": "วงศ์ชัย", "romanized": "Wongchai"}'::jsonb,true,3),
('surname','saetang','{"thai": "แซ่ตัง", "romanized": "Saetang"}'::jsonb,true,4),
('surname','thongdee','{"thai": "ทองดี", "romanized": "Thongdee"}'::jsonb,true,5),
('surname','boonmee','{"thai": "บุญมี", "romanized": "Boonmee"}'::jsonb,true,6),
('surname','srisawat','{"thai": "ศรีสวัสดิ์", "romanized": "Srisawat"}'::jsonb,true,7),
('surname','limwattana','{"thai": "ลิ้มวัฒนา", "romanized": "Limwattana"}'::jsonb,true,8),
('surname','wattana','{"thai": "วัฒนา", "romanized": "Wattana"}'::jsonb,true,9),
('surname','phromma','{"thai": "พรหมมา", "romanized": "Phromma"}'::jsonb,true,10),
('surname','saengchan','{"thai": "แสงจันทร์", "romanized": "Saengchan"}'::jsonb,true,11),
('surname','tansakul','{"thai": "ตันสกุล", "romanized": "Tansakul"}'::jsonb,true,12),
('surname','bunnak','{"thai": "บุนนาค", "romanized": "Bunnak"}'::jsonb,true,13),
('surname','charoen','{"thai": "เจริญ", "romanized": "Charoen"}'::jsonb,true,14),
('surname','deeprasert','{"thai": "ดีประเสริฐ", "romanized": "Deeprasert"}'::jsonb,true,15),
('surname','kaewmanee','{"thai": "แก้วมณี", "romanized": "Kaewmanee"}'::jsonb,true,16),
('surname','laohakul','{"thai": "เลาหะกุล", "romanized": "Laohakul"}'::jsonb,true,17),
('surname','meesuk','{"thai": "มีสุข", "romanized": "Meesuk"}'::jsonb,true,18),
('surname','sangthong','{"thai": "แสงทอง", "romanized": "Sangthong"}'::jsonb,true,19),
('surname','thipwong','{"thai": "ทิพย์วงศ์", "romanized": "Thipwong"}'::jsonb,true,20),
('surname','udomsuk','{"thai": "อุดมสุข", "romanized": "Udomsuk"}'::jsonb,true,21),
('surname','wongsawat','{"thai": "วงศ์สวัสดิ์", "romanized": "Wongsawat"}'::jsonb,true,22),
('surname','boonprasert','{"thai": "บุญประเสริฐ", "romanized": "Boonprasert"}'::jsonb,true,23),
('surname','chaiyanan','{"thai": "ชัยนันท์", "romanized": "Chaiyanan"}'::jsonb,true,24),
('surname','duangjan','{"thai": "ดวงจันทร์", "romanized": "Duangjan"}'::jsonb,true,25),
('surname','homhuan','{"thai": "หอมหวน", "romanized": "Homhuan"}'::jsonb,true,26),
('surname','kongkaew','{"thai": "กองแก้ว", "romanized": "Kongkaew"}'::jsonb,true,27),
('surname','lertchai','{"thai": "เลิศชัย", "romanized": "Lertchai"}'::jsonb,true,28),
('surname','maneechai','{"thai": "มณีชัย", "romanized": "Maneechai"}'::jsonb,true,29),
('surname','noppakun','{"thai": "นพกุล", "romanized": "Noppakun"}'::jsonb,true,30),
('surname','panyachai','{"thai": "ปัญญาชัย", "romanized": "Panyachai"}'::jsonb,true,31),
('surname','rattanakul','{"thai": "รัตนากุล", "romanized": "Rattanakul"}'::jsonb,true,32),
('surname','siripong','{"thai": "ศิริพงษ์", "romanized": "Siripong"}'::jsonb,true,33),
('surname','thanomsak','{"thai": "ถนอมศักดิ์", "romanized": "Thanomsak"}'::jsonb,true,34),
('surname','boonchai','{"thai": "บุญชัย", "romanized": "Boonchai"}'::jsonb,true,35),
('surname','chuenchom','{"thai": "ชื่นชม", "romanized": "Chuenchom"}'::jsonb,true,36),
('surname','hongthong','{"thai": "หงษ์ทอง", "romanized": "Hongthong"}'::jsonb,true,37),
('surname','kaewsai','{"thai": "แก้วใส", "romanized": "Kaewsai"}'::jsonb,true,38),
('surname','meechai','{"thai": "มีชัย", "romanized": "Meechai"}'::jsonb,true,39),
('surname','phromchai','{"thai": "พรหมชัย", "romanized": "Phromchai"}'::jsonb,true,40),
('surname','saengsuk','{"thai": "แสงสุข", "romanized": "Saengsuk"}'::jsonb,true,41),
('surname','thongchai','{"thai": "ทองชัย", "romanized": "Thongchai"}'::jsonb,true,42),
('surname','sangwan','{"thai": "สังวาลย์", "romanized": "Sangwan"}'::jsonb,true,43),
('surname','praphat','{"thai": "ประพัทธ์", "romanized": "Praphat"}'::jsonb,true,44),
('surname','yimyam','{"thai": "ยิ้มแย้ม", "romanized": "Yimyam"}'::jsonb,true,45),
('surname','anantakul','{"thai": "อนันตกุล", "romanized": "Anantakul"}'::jsonb,true,46),
('surname','vichit','{"thai": "วิจิตร", "romanized": "Vichit"}'::jsonb,true,47),
('surname','rojanasiri','{"thai": "โรจนศิริ", "romanized": "Rojanasiri"}'::jsonb,true,48),
('surname','inthong','{"thai": "อินทอง", "romanized": "Inthong"}'::jsonb,true,49),
('surname','jindarat','{"thai": "จินดารัตน์", "romanized": "Jindarat"}'::jsonb,true,50),
('surname','yodthong','{"thai": "ยอดทอง", "romanized": "Yodthong"}'::jsonb,true,51),
('surname','apirak','{"thai": "อภิรักษ์", "romanized": "Apirak"}'::jsonb,true,52),
('surname','wichan','{"thai": "วิจารณ์", "romanized": "Wichan"}'::jsonb,true,53),
('surname','yodrak','{"thai": "ยอดรัก", "romanized": "Yodrak"}'::jsonb,true,54),
('surname','fuangfu','{"thai": "เฟื่องฟู", "romanized": "Fuangfu"}'::jsonb,true,55),
('surname','gansuk','{"thai": "แก่นสุข", "romanized": "Gansuk"}'::jsonb,true,56),
('surname','hongsa','{"thai": "หงษา", "romanized": "Hongsa"}'::jsonb,true,57),
('surname','inthasiri','{"thai": "อินทศิริ", "romanized": "Inthasiri"}'::jsonb,true,58),
('surname','jirapong','{"thai": "จิรพงษ์", "romanized": "Jirapong"}'::jsonb,true,59),
('surname','lueangchai','{"thai": "เหลืองชัย", "romanized": "Lueangchai"}'::jsonb,true,60),
('surname','noknoi','{"thai": "นกน้อย", "romanized": "Noknoi"}'::jsonb,true,61),
('surname','orachun','{"thai": "อรชุน", "romanized": "Orachun"}'::jsonb,true,62),
('surname','upathum','{"thai": "อุปถัมภ์", "romanized": "Upathum"}'::jsonb,true,63),
('surname','vanich','{"thai": "วานิช", "romanized": "Vanich"}'::jsonb,true,64),
('surname','wiroon','{"thai": "วิรุฬห์", "romanized": "Wiroon"}'::jsonb,true,65),
('surname','anekchai','{"thai": "อเนกชัย", "romanized": "Anekchai"}'::jsonb,true,66),
('surname','chaiyaporn','{"thai": "ชัยพร", "romanized": "Chaiyaporn"}'::jsonb,true,67),
('surname','intharachai','{"thai": "อินทรชัย", "romanized": "Intharachai"}'::jsonb,true,68),
('surname','nakhonthai','{"thai": "นครไทย", "romanized": "Nakhonthai"}'::jsonb,true,69),
('surname','pradit','{"thai": "ประดิษฐ์", "romanized": "Pradit"}'::jsonb,true,70),
('surname','chuenchit','{"thai": "ชื่นจิต", "romanized": "Chuenchit"}'::jsonb,true,71),
('surname','yodchai','{"thai": "ยอดชัย", "romanized": "Yodchai"}'::jsonb,true,72),
('surname','ekkasit','{"thai": "เอกสิทธิ์", "romanized": "Ekkasit"}'::jsonb,true,73),
('surname','narongchai','{"thai": "ณรงค์ชัย", "romanized": "Narongchai"}'::jsonb,true,74),
('surname','ongart','{"thai": "องอาจ", "romanized": "Ongart"}'::jsonb,true,75),
('surname','phukhao','{"thai": "ภูเขา", "romanized": "Phukhao"}'::jsonb,true,76),
('surname','phongpan','{"thai": "พงษ์พาน", "romanized": "Phongpan"}'::jsonb,true,77),
('surname','ratanaporn','{"thai": "รัตนพร", "romanized": "Ratanaporn"}'::jsonb,true,78),
('surname','deephrom','{"thai": "ดีพรหม", "romanized": "Deephrom"}'::jsonb,true,79),
('surname','faengchan','{"thai": "แฝงจันทร์", "romanized": "Faengchan"}'::jsonb,true,80)
ON CONFLICT (kind,code) DO UPDATE SET payload=EXCLUDED.payload, updated_at=now();

INSERT INTO public.custom_ausiris_demo_config (kind,code,payload,is_active,sort_order) VALUES
('nickname','ton','{"thai": "ต้น", "romanized": "Ton"}'::jsonb,true,1),
('nickname','mint','{"thai": "มิ้น", "romanized": "Mint"}'::jsonb,true,2),
('nickname','ball','{"thai": "บอล", "romanized": "Ball"}'::jsonb,true,3),
('nickname','jane','{"thai": "เจน", "romanized": "Jane"}'::jsonb,true,4),
('nickname','oak','{"thai": "โอ๊ค", "romanized": "Oak"}'::jsonb,true,5),
('nickname','fern','{"thai": "เฟิร์น", "romanized": "Fern"}'::jsonb,true,6),
('nickname','bew','{"thai": "บิว", "romanized": "Bew"}'::jsonb,true,7),
('nickname','non','{"thai": "นน", "romanized": "Non"}'::jsonb,true,8),
('nickname','tum','{"thai": "ตั้ม", "romanized": "Tum"}'::jsonb,true,9),
('nickname','belle','{"thai": "เบล", "romanized": "Belle"}'::jsonb,true,10),
('nickname','pat','{"thai": "แพท", "romanized": "Pat"}'::jsonb,true,11),
('nickname','jay','{"thai": "เจ", "romanized": "Jay"}'::jsonb,true,12),
('nickname','m','{"thai": "เอ็ม", "romanized": "Em"}'::jsonb,true,13),
('nickname','gun','{"thai": "กัน", "romanized": "Gun"}'::jsonb,true,14),
('nickname','four','{"thai": "โฟร์", "romanized": "Four"}'::jsonb,true,15),
('nickname','nine','{"thai": "เก้า", "romanized": "Kao"}'::jsonb,true,16),
('nickname','fay','{"thai": "เฟย", "romanized": "Fay"}'::jsonb,true,17),
('nickname','ta','{"thai": "ต้า", "romanized": "Ta"}'::jsonb,true,18),
('nickname','noey','{"thai": "เนย", "romanized": "Noey"}'::jsonb,true,19),
('nickname','por','{"thai": "ปอ", "romanized": "Por"}'::jsonb,true,20),
('nickname','champ','{"thai": "แชมป์", "romanized": "Champ"}'::jsonb,true,21),
('nickname','mick','{"thai": "มิก", "romanized": "Mick"}'::jsonb,true,22),
('nickname','benz','{"thai": "เบนซ์", "romanized": "Benz"}'::jsonb,true,23),
('nickname','taeng','{"thai": "แตง", "romanized": "Taeng"}'::jsonb,true,24),
('nickname','nam','{"thai": "น้ำ", "romanized": "Nam"}'::jsonb,true,25),
('nickname','kwan','{"thai": "ขวัญ", "romanized": "Kwan"}'::jsonb,true,26),
('nickname','gale','{"thai": "เกล", "romanized": "Gale"}'::jsonb,true,27),
('nickname','prae','{"thai": "แพร", "romanized": "Prae"}'::jsonb,true,28),
('nickname','big','{"thai": "บิ๊ก", "romanized": "Big"}'::jsonb,true,29),
('nickname','earth','{"thai": "เอิร์ธ", "romanized": "Earth"}'::jsonb,true,30)
ON CONFLICT (kind,code) DO UPDATE SET payload=EXCLUDED.payload, updated_at=now();

INSERT INTO public.custom_ausiris_demo_config (kind,code,payload,is_active,sort_order) VALUES
('archetype','whale_trader','{"weight":0.06,"n_buy_min":10,"n_buy_max":18,"last_buy_max_days":14,"lob":"spot_gold","tier_bias":"platinum","act_n":18}'::jsonb,true,1),
('archetype','loyal_saver','{"weight":0.18,"n_buy_min":4,"n_buy_max":6,"last_buy_max_days":20,"lob":"gold_saving","tier_bias":"gold","act_n":10}'::jsonb,true,2),
('archetype','bar_shopper','{"weight":0.14,"n_buy_min":2,"n_buy_max":4,"last_buy_max_days":45,"lob":"small_bar","tier_bias":"silver","act_n":6}'::jsonb,true,3),
('archetype','jewelry_gifter','{"weight":0.12,"n_buy_min":1,"n_buy_max":3,"last_buy_max_days":60,"lob":"jewelry","tier_bias":"silver","act_n":8}'::jsonb,true,4),
('archetype','cooling_vip','{"weight":0.08,"n_buy_min":4,"n_buy_max":8,"last_buy_min_days":45,"last_buy_max_days":90,"lob":"spot_gold","tier_bias":"gold","act_n":8}'::jsonb,true,5),
('archetype','hibernating','{"weight":0.10,"n_buy_min":1,"n_buy_max":2,"last_buy_min_days":160,"last_buy_max_days":180,"lob":"mixed","tier_bias":"silver","act_n":1}'::jsonb,true,6),
('archetype','high_intent_unpaid','{"weight":0.12,"n_buy_min":0,"n_buy_max":0,"last_buy_max_days":null,"lob":null,"tier_bias":"silver","act_n":12}'::jsonb,true,7),
('archetype','new_lead','{"weight":0.10,"n_buy_min":0,"n_buy_max":0,"last_buy_max_days":null,"lob":null,"tier_bias":"silver","act_n":3}'::jsonb,true,8),
('archetype','first_purchase','{"weight":0.08,"n_buy_min":1,"n_buy_max":1,"last_buy_min_days":14,"last_buy_max_days":28,"lob":"gold_saving","tier_bias":"silver","act_n":5}'::jsonb,true,9),
('archetype','omni_program','{"weight":0.02,"n_buy_min":6,"n_buy_max":10,"last_buy_max_days":21,"lob":"mixed","tier_bias":"gold","act_n":16}'::jsonb,true,10)
ON CONFLICT (kind,code) DO UPDATE SET payload=EXCLUDED.payload, updated_at=now();

INSERT INTO public.custom_ausiris_demo_config (kind,code,payload,is_active,sort_order) VALUES
('named','C0','{"seq":1,"phone":"0812345678","archetype":"omni_program","role":"canonical"}'::jsonb,true,0),
('named','C1','{"seq":2,"phone":"0812345601","archetype":"whale_trader","role":"champion_trader"}'::jsonb,true,1),
('named','C2','{"seq":3,"phone":"0812345602","archetype":"loyal_saver","role":"loyal_saver"}'::jsonb,true,2),
('named','C3','{"seq":4,"phone":"0812345603","archetype":"bar_shopper","role":"bar_tonglek"}'::jsonb,true,3),
('named','C4','{"seq":5,"phone":"0812345604","archetype":"jewelry_gifter","role":"jewelry"}'::jsonb,true,4),
('named','C5','{"seq":6,"phone":"0812345605","archetype":"cooling_vip","role":"cooling_vip"}'::jsonb,true,5),
('named','C6','{"seq":7,"phone":"0812345606","archetype":"cooling_vip","role":"recovered"}'::jsonb,true,6),
('named','C7','{"seq":8,"phone":"0812345607","archetype":"hibernating","role":"hibernating"}'::jsonb,true,7),
('named','C8','{"seq":9,"phone":"0812345608","archetype":"high_intent_unpaid","role":"unpaid"}'::jsonb,true,8),
('named','C9','{"seq":10,"phone":"0812345609","archetype":"new_lead","role":"welcome"}'::jsonb,true,9),
('named','C10','{"seq":11,"phone":"0812345610","archetype":"first_purchase","role":"first_purchase"}'::jsonb,true,10),
('named','C11','{"seq":12,"phone":"0812345611","archetype":"bar_shopper","role":"silver_pos"}'::jsonb,true,11)
ON CONFLICT (kind,code) DO UPDATE SET payload=EXCLUDED.payload, updated_at=now();

INSERT INTO public.custom_ausiris_demo_config (kind,code,payload,is_active,sort_order) VALUES
('settings','default','{"merchant_id":"b7794d29-2df7-47e2-a707-5654fe9f71c4","merchant_code":"ausiris","seed_tag":"SEED-AUS-V2","target_members":10000,"seed_days":180,"points_per_thb":0.1}'::jsonb,true,0)
ON CONFLICT (kind,code) DO UPDATE SET payload=EXCLUDED.payload, updated_at=now();

