-- Authored pools for Rocket Demo generator
INSERT INTO public.custom_internal_demo_config (kind,code,payload,is_active,sort_order) VALUES
('given_name','nara','{"thai": "นารา", "romanized": "Nara", "gender": "f"}'::jsonb,true,1),
('given_name','pim','{"thai": "พิมพ์", "romanized": "Pim", "gender": "f"}'::jsonb,true,2),
('given_name','praew','{"thai": "แพรว", "romanized": "Praew", "gender": "f"}'::jsonb,true,3),
('given_name','ploy','{"thai": "พลอย", "romanized": "Ploy", "gender": "f"}'::jsonb,true,4),
('given_name','namwan','{"thai": "น้ำหวาน", "romanized": "Namwan", "gender": "f"}'::jsonb,true,5),
('given_name','fah','{"thai": "ฟ้า", "romanized": "Fah", "gender": "f"}'::jsonb,true,6),
('given_name','mint','{"thai": "มิ้นท์", "romanized": "Mint", "gender": "f"}'::jsonb,true,7),
('given_name','fern','{"thai": "เฟิร์น", "romanized": "Fern", "gender": "f"}'::jsonb,true,8),
('given_name','may','{"thai": "เมย์", "romanized": "May", "gender": "f"}'::jsonb,true,9),
('given_name','nicha','{"thai": "ณิชา", "romanized": "Nicha", "gender": "f"}'::jsonb,true,10),
('given_name','kanokwan','{"thai": "กนกวรรณ", "romanized": "Kanokwan", "gender": "f"}'::jsonb,true,11),
('given_name','siriporn','{"thai": "ศิริพร", "romanized": "Siriporn", "gender": "f"}'::jsonb,true,12),
('given_name','wanida','{"thai": "วนิดา", "romanized": "Wanida", "gender": "f"}'::jsonb,true,13),
('given_name','apinya','{"thai": "อภิญญา", "romanized": "Apinya", "gender": "f"}'::jsonb,true,14),
('given_name','chuthamat','{"thai": "จุฑามาศ", "romanized": "Chuthamat", "gender": "f"}'::jsonb,true,15),
('given_name','kanyarat','{"thai": "กัญญารัตน์", "romanized": "Kanyarat", "gender": "f"}'::jsonb,true,16),
('given_name','supaporn','{"thai": "สุภาพร", "romanized": "Supaporn", "gender": "f"}'::jsonb,true,17),
('given_name','oranong','{"thai": "อรอนงค์", "romanized": "Oranong", "gender": "f"}'::jsonb,true,18),
('given_name','patcharee','{"thai": "พัชรี", "romanized": "Patcharee", "gender": "f"}'::jsonb,true,19),
('given_name','ratchanok','{"thai": "รัชนก", "romanized": "Ratchanok", "gender": "f"}'::jsonb,true,20),
('given_name','thanyarat','{"thai": "ธัญรัตน์", "romanized": "Thanyarat", "gender": "f"}'::jsonb,true,21),
('given_name','warunee','{"thai": "วารุณี", "romanized": "Warunee", "gender": "f"}'::jsonb,true,22),
('given_name','jiraporn','{"thai": "จิราพร", "romanized": "Jiraporn", "gender": "f"}'::jsonb,true,23),
('given_name','nattaya','{"thai": "ณัฐยา", "romanized": "Nattaya", "gender": "f"}'::jsonb,true,24),
('given_name','panida','{"thai": "พนิดา", "romanized": "Panida", "gender": "f"}'::jsonb,true,25),
('given_name','siriwan','{"thai": "ศิริวรรณ", "romanized": "Siriwan", "gender": "f"}'::jsonb,true,26),
('given_name','anong','{"thai": "อนงค์", "romanized": "Anong", "gender": "f"}'::jsonb,true,27),
('given_name','busakorn','{"thai": "บุษกร", "romanized": "Busakorn", "gender": "f"}'::jsonb,true,28),
('given_name','chanida','{"thai": "ชนิดา", "romanized": "Chanida", "gender": "f"}'::jsonb,true,29),
('given_name','duangjai','{"thai": "ดวงใจ", "romanized": "Duangjai", "gender": "f"}'::jsonb,true,30),
('given_name','arisa','{"thai": "อริสา", "romanized": "Arisa", "gender": "f"}'::jsonb,true,31),
('given_name','benjawan','{"thai": "เบญจวรรณ", "romanized": "Benjawan", "gender": "f"}'::jsonb,true,32),
('given_name','chompoo','{"thai": "ชมพู่", "romanized": "Chompoo", "gender": "f"}'::jsonb,true,33),
('given_name','dao','{"thai": "ดาว", "romanized": "Dao", "gender": "f"}'::jsonb,true,34),
('given_name','fon','{"thai": "ฝน", "romanized": "Fon", "gender": "f"}'::jsonb,true,35),
('given_name','kamonchanok','{"thai": "กมลชนก", "romanized": "Kamonchanok", "gender": "f"}'::jsonb,true,36),
('given_name','pimchanok','{"thai": "พิมพ์ชนก", "romanized": "Pimchanok", "gender": "f"}'::jsonb,true,37),
('given_name','supawadee','{"thai": "สุภาวดี", "romanized": "Supawadee", "gender": "f"}'::jsonb,true,38),
('given_name','orawan','{"thai": "อรวรรณ", "romanized": "Orawan", "gender": "f"}'::jsonb,true,39),
('given_name','chayanit','{"thai": "ชญานิษฐ์", "romanized": "Chayanit", "gender": "f"}'::jsonb,true,40),
('given_name','thanaporn','{"thai": "ธนพร", "romanized": "Thanaporn", "gender": "f"}'::jsonb,true,41),
('given_name','wipada','{"thai": "วิภาดา", "romanized": "Wipada", "gender": "f"}'::jsonb,true,42),
('given_name','anucha','{"thai": "อนุชา", "romanized": "Anucha", "gender": "m"}'::jsonb,true,43),
('given_name','somchai','{"thai": "สมชาย", "romanized": "Somchai", "gender": "m"}'::jsonb,true,44),
('given_name','surachai','{"thai": "สุรชัย", "romanized": "Surachai", "gender": "m"}'::jsonb,true,45),
('given_name','pramote','{"thai": "ปราโมทย์", "romanized": "Pramote", "gender": "m"}'::jsonb,true,46),
('given_name','wichai','{"thai": "วิชัย", "romanized": "Wichai", "gender": "m"}'::jsonb,true,47),
('given_name','thanakorn','{"thai": "ธนากร", "romanized": "Thanakorn", "gender": "m"}'::jsonb,true,48),
('given_name','kittisak','{"thai": "กิตติศักดิ์", "romanized": "Kittisak", "gender": "m"}'::jsonb,true,49),
('given_name','nattapong','{"thai": "ณัฐพงศ์", "romanized": "Nattapong", "gender": "m"}'::jsonb,true,50),
('given_name','apichat','{"thai": "อภิชาติ", "romanized": "Apichat", "gender": "m"}'::jsonb,true,51),
('given_name','boonlert','{"thai": "บุญเลิศ", "romanized": "Boonlert", "gender": "m"}'::jsonb,true,52),
('given_name','chatchai','{"thai": "ฉัตรชัย", "romanized": "Chatchai", "gender": "m"}'::jsonb,true,53),
('given_name','danai','{"thai": "ดนัย", "romanized": "Danai", "gender": "m"}'::jsonb,true,54),
('given_name','ekkachai','{"thai": "เอกชัย", "romanized": "Ekkachai", "gender": "m"}'::jsonb,true,55),
('given_name','ittipol','{"thai": "อิทธิพล", "romanized": "Ittipol", "gender": "m"}'::jsonb,true,56),
('given_name','jakkrit','{"thai": "จักรฤทธิ์", "romanized": "Jakkrit", "gender": "m"}'::jsonb,true,57),
('given_name','kritsada','{"thai": "กฤษฎา", "romanized": "Kritsada", "gender": "m"}'::jsonb,true,58),
('given_name','manop','{"thai": "มานพ", "romanized": "Manop", "gender": "m"}'::jsonb,true,59),
('given_name','narong','{"thai": "ณรงค์", "romanized": "Narong", "gender": "m"}'::jsonb,true,60),
('given_name','phichai','{"thai": "พิชัย", "romanized": "Phichai", "gender": "m"}'::jsonb,true,61),
('given_name','sakchai','{"thai": "ศักดิ์ชัย", "romanized": "Sakchai", "gender": "m"}'::jsonb,true,62),
('given_name','thana','{"thai": "ธนา", "romanized": "Thana", "gender": "m"}'::jsonb,true,63),
('given_name','udom','{"thai": "อุดม", "romanized": "Udom", "gender": "m"}'::jsonb,true,64),
('given_name','vorawut','{"thai": "วรวุฒิ", "romanized": "Vorawut", "gender": "m"}'::jsonb,true,65),
('given_name','yuthana','{"thai": "ยุทธนา", "romanized": "Yuthana", "gender": "m"}'::jsonb,true,66),
('given_name','weerachai','{"thai": "วีรชัย", "romanized": "Weerachai", "gender": "m"}'::jsonb,true,67),
('given_name','anuwat','{"thai": "อนุวัฒน์", "romanized": "Anuwat", "gender": "m"}'::jsonb,true,68),
('given_name','peerapat','{"thai": "พีรพัฒน์", "romanized": "Peerapat", "gender": "m"}'::jsonb,true,69),
('given_name','tanawat','{"thai": "ธนวัฒน์", "romanized": "Tanawat", "gender": "m"}'::jsonb,true,70),
('given_name','napat','{"thai": "ณภัทร", "romanized": "Napat", "gender": "m"}'::jsonb,true,71),
('given_name','siwat','{"thai": "ศิวัต", "romanized": "Siwat", "gender": "m"}'::jsonb,true,72),
('given_name','kamon','{"thai": "กมล", "romanized": "Kamon", "gender": "u"}'::jsonb,true,73),
('given_name','isara','{"thai": "อิสรา", "romanized": "Isara", "gender": "u"}'::jsonb,true,74)
ON CONFLICT (kind,code) DO UPDATE SET payload=EXCLUDED.payload, updated_at=now();
INSERT INTO public.custom_internal_demo_config (kind,code,payload,is_active,sort_order) VALUES
('surname','sukkasem','{"thai": "สุขเกษม", "romanized": "Sukkasem"}'::jsonb,true,1),
('surname','chaisiri','{"thai": "ชัยศิริ", "romanized": "Chaisiri"}'::jsonb,true,2),
('surname','wongchai','{"thai": "วงศ์ชัย", "romanized": "Wongchai"}'::jsonb,true,3),
('surname','saetang','{"thai": "แซ่ตัง", "romanized": "Saetang"}'::jsonb,true,4),
('surname','thongdee','{"thai": "ทองดี", "romanized": "Thongdee"}'::jsonb,true,5),
('surname','boonmee','{"thai": "บุญมี", "romanized": "Boonmee"}'::jsonb,true,6),
('surname','srisawat','{"thai": "ศรีสวัสดิ์", "romanized": "Srisawat"}'::jsonb,true,7),
('surname','limwattana','{"thai": "ลิ้มวัฒนา", "romanized": "Limwattana"}'::jsonb,true,8),
('surname','wattana','{"thai": "วัฒนา", "romanized": "Wattana"}'::jsonb,true,9),
('surname','phromma','{"thai": "พรหมมา", "romanized": "Phromma"}'::jsonb,true,10),
('surname','saengchan','{"thai": "แสงจันทร์", "romanized": "Saengchan"}'::jsonb,true,11),
('surname','tansakul','{"thai": "ตันสกุล", "romanized": "Tansakul"}'::jsonb,true,12),
('surname','bunnak','{"thai": "บุนนาค", "romanized": "Bunnak"}'::jsonb,true,13),
('surname','charoen','{"thai": "เจริญ", "romanized": "Charoen"}'::jsonb,true,14),
('surname','deeprasert','{"thai": "ดีประเสริฐ", "romanized": "Deeprasert"}'::jsonb,true,15),
('surname','kaewmanee','{"thai": "แก้วมณี", "romanized": "Kaewmanee"}'::jsonb,true,16),
('surname','laohakul','{"thai": "เลาหะกุล", "romanized": "Laohakul"}'::jsonb,true,17),
('surname','meesuk','{"thai": "มีสุข", "romanized": "Meesuk"}'::jsonb,true,18),
('surname','sangthong','{"thai": "แสงทอง", "romanized": "Sangthong"}'::jsonb,true,19),
('surname','thipwong','{"thai": "ทิพย์วงศ์", "romanized": "Thipwong"}'::jsonb,true,20),
('surname','udomsuk','{"thai": "อุดมสุข", "romanized": "Udomsuk"}'::jsonb,true,21),
('surname','wongsawat','{"thai": "วงศ์สวัสดิ์", "romanized": "Wongsawat"}'::jsonb,true,22),
('surname','boonprasert','{"thai": "บุญประเสริฐ", "romanized": "Boonprasert"}'::jsonb,true,23),
('surname','chaiyanan','{"thai": "ชัยนันท์", "romanized": "Chaiyanan"}'::jsonb,true,24),
('surname','duangjan','{"thai": "ดวงจันทร์", "romanized": "Duangjan"}'::jsonb,true,25),
('surname','homhuan','{"thai": "หอมหวน", "romanized": "Homhuan"}'::jsonb,true,26),
('surname','kongkaew','{"thai": "กองแก้ว", "romanized": "Kongkaew"}'::jsonb,true,27),
('surname','lertchai','{"thai": "เลิศชัย", "romanized": "Lertchai"}'::jsonb,true,28),
('surname','maneechai','{"thai": "มณีชัย", "romanized": "Maneechai"}'::jsonb,true,29),
('surname','noppakun','{"thai": "นพกุล", "romanized": "Noppakun"}'::jsonb,true,30),
('surname','panyachai','{"thai": "ปัญญาชัย", "romanized": "Panyachai"}'::jsonb,true,31),
('surname','rattanakul','{"thai": "รัตนากุล", "romanized": "Rattanakul"}'::jsonb,true,32),
('surname','siripong','{"thai": "ศิริพงษ์", "romanized": "Siripong"}'::jsonb,true,33),
('surname','thanomsak','{"thai": "ถนอมศักดิ์", "romanized": "Thanomsak"}'::jsonb,true,34),
('surname','boonchai','{"thai": "บุญชัย", "romanized": "Boonchai"}'::jsonb,true,35),
('surname','chuenchom','{"thai": "ชื่นชม", "romanized": "Chuenchom"}'::jsonb,true,36),
('surname','hongthong','{"thai": "หงษ์ทอง", "romanized": "Hongthong"}'::jsonb,true,37),
('surname','kaewsai','{"thai": "แก้วใส", "romanized": "Kaewsai"}'::jsonb,true,38),
('surname','meechai','{"thai": "มีชัย", "romanized": "Meechai"}'::jsonb,true,39),
('surname','phromchai','{"thai": "พรหมชัย", "romanized": "Phromchai"}'::jsonb,true,40),
('surname','saengsuk','{"thai": "แสงสุข", "romanized": "Saengsuk"}'::jsonb,true,41),
('surname','thongchai','{"thai": "ทองชัย", "romanized": "Thongchai"}'::jsonb,true,42),
('surname','sangwan','{"thai": "สังวาลย์", "romanized": "Sangwan"}'::jsonb,true,43),
('surname','praphat','{"thai": "ประพัทธ์", "romanized": "Praphat"}'::jsonb,true,44),
('surname','yimyam','{"thai": "ยิ้มแย้ม", "romanized": "Yimyam"}'::jsonb,true,45),
('surname','anantakul','{"thai": "อนันตกุล", "romanized": "Anantakul"}'::jsonb,true,46),
('surname','vichit','{"thai": "วิจิตร", "romanized": "Vichit"}'::jsonb,true,47),
('surname','rojanasiri','{"thai": "โรจนศิริ", "romanized": "Rojanasiri"}'::jsonb,true,48),
('surname','inthong','{"thai": "อินทอง", "romanized": "Inthong"}'::jsonb,true,49),
('surname','jindarat','{"thai": "จินดารัตน์", "romanized": "Jindarat"}'::jsonb,true,50),
('surname','yodthong','{"thai": "ยอดทอง", "romanized": "Yodthong"}'::jsonb,true,51),
('surname','apirak','{"thai": "อภิรักษ์", "romanized": "Apirak"}'::jsonb,true,52),
('surname','wichan','{"thai": "วิจารณ์", "romanized": "Wichan"}'::jsonb,true,53),
('surname','yodrak','{"thai": "ยอดรัก", "romanized": "Yodrak"}'::jsonb,true,54),
('surname','fuangfu','{"thai": "เฟื่องฟู", "romanized": "Fuangfu"}'::jsonb,true,55),
('surname','gansuk','{"thai": "แก่นสุข", "romanized": "Gansuk"}'::jsonb,true,56),
('surname','hongsa','{"thai": "หงษา", "romanized": "Hongsa"}'::jsonb,true,57),
('surname','inthasiri','{"thai": "อินทศิริ", "romanized": "Inthasiri"}'::jsonb,true,58),
('surname','jirapong','{"thai": "จิรพงษ์", "romanized": "Jirapong"}'::jsonb,true,59),
('surname','lueangchai','{"thai": "เหลืองชัย", "romanized": "Lueangchai"}'::jsonb,true,60),
('surname','noknoi','{"thai": "นกน้อย", "romanized": "Noknoi"}'::jsonb,true,61),
('surname','orachun','{"thai": "อรชุน", "romanized": "Orachun"}'::jsonb,true,62),
('surname','upathum','{"thai": "อุปถัมภ์", "romanized": "Upathum"}'::jsonb,true,63),
('surname','vanich','{"thai": "วานิช", "romanized": "Vanich"}'::jsonb,true,64),
('surname','wiroon','{"thai": "วิรุฬห์", "romanized": "Wiroon"}'::jsonb,true,65),
('surname','anekchai','{"thai": "อเนกชัย", "romanized": "Anekchai"}'::jsonb,true,66),
('surname','chaiyaporn','{"thai": "ชัยพร", "romanized": "Chaiyaporn"}'::jsonb,true,67),
('surname','intharachai','{"thai": "อินทรชัย", "romanized": "Intharachai"}'::jsonb,true,68),
('surname','nakhonthai','{"thai": "นครไทย", "romanized": "Nakhonthai"}'::jsonb,true,69),
('surname','pradit','{"thai": "ประดิษฐ์", "romanized": "Pradit"}'::jsonb,true,70),
('surname','chuenchit','{"thai": "ชื่นจิต", "romanized": "Chuenchit"}'::jsonb,true,71),
('surname','yodchai','{"thai": "ยอดชัย", "romanized": "Yodchai"}'::jsonb,true,72),
('surname','ekkasit','{"thai": "เอกสิทธิ์", "romanized": "Ekkasit"}'::jsonb,true,73),
('surname','narongchai','{"thai": "ณรงค์ชัย", "romanized": "Narongchai"}'::jsonb,true,74),
('surname','ongart','{"thai": "องอาจ", "romanized": "Ongart"}'::jsonb,true,75),
('surname','phukhao','{"thai": "ภูเขา", "romanized": "Phukhao"}'::jsonb,true,76),
('surname','phongpan','{"thai": "พงษ์พาน", "romanized": "Phongpan"}'::jsonb,true,77),
('surname','ratanaporn','{"thai": "รัตนพร", "romanized": "Ratanaporn"}'::jsonb,true,78),
('surname','deephrom','{"thai": "ดีพรหม", "romanized": "Deephrom"}'::jsonb,true,79),
('surname','faengchan','{"thai": "แฝงจันทร์", "romanized": "Faengchan"}'::jsonb,true,80)
ON CONFLICT (kind,code) DO UPDATE SET payload=EXCLUDED.payload, updated_at=now();
INSERT INTO public.custom_internal_demo_config (kind,code,payload,is_active,sort_order) VALUES
('product','RG-CLN-001','{"name": "Gentle Rice Cleansing Foam 150ml", "brand": "RiceGlow", "category": "Cleanse", "price": 390, "sku_code": "RG-CLN-001"}'::jsonb,true,1),
('product','RG-CLN-002','{"name": "Micellar Rice Water Cleanser 200ml", "brand": "RiceGlow", "category": "Cleanse", "price": 320, "sku_code": "RG-CLN-002"}'::jsonb,true,2),
('product','RG-CLN-003','{"name": "Oil-to-Milk Makeup Remover 100ml", "brand": "RiceGlow", "category": "Cleanse", "price": 450, "sku_code": "RG-CLN-003"}'::jsonb,true,3),
('product','RG-CLN-004','{"name": "Enzyme Powder Wash 60g", "brand": "RiceGlow", "category": "Cleanse", "price": 490, "sku_code": "RG-CLN-004"}'::jsonb,true,4),
('product','RG-CLN-005','{"name": "Calming Gel Cleanser 120ml", "brand": "AloePure", "category": "Cleanse", "price": 289, "sku_code": "RG-CLN-005"}'::jsonb,true,5),
('product','RG-CLN-006','{"name": "Charcoal Detox Foam 150ml", "brand": "UrbanSkin", "category": "Cleanse", "price": 349, "sku_code": "RG-CLN-006"}'::jsonb,true,6),
('product','RG-CLN-007','{"name": "Amino Acid Cream Cleanser 100ml", "brand": "SilkDerm", "category": "Cleanse", "price": 420, "sku_code": "RG-CLN-007"}'::jsonb,true,7),
('product','RG-CLN-008','{"name": "Green Tea Balancing Toner Pads 60pcs", "brand": "MatchaLab", "category": "Cleanse", "price": 399, "sku_code": "RG-CLN-008"}'::jsonb,true,8),
('product','RG-TRT-001','{"name": "Niacinamide Bright Serum 30ml", "brand": "GlowLab", "category": "Treat", "price": 590, "sku_code": "RG-TRT-001"}'::jsonb,true,9),
('product','RG-TRT-002','{"name": "Vitamin C Spot Corrector 20ml", "brand": "GlowLab", "category": "Treat", "price": 690, "sku_code": "RG-TRT-002"}'::jsonb,true,10),
('product','RG-TRT-003','{"name": "Retinol Night Repair 30ml", "brand": "AgeSoft", "category": "Treat", "price": 890, "sku_code": "RG-TRT-003"}'::jsonb,true,11),
('product','RG-TRT-004','{"name": "Hyaluronic Moisture Ampoule 50ml", "brand": "AquaLayer", "category": "Treat", "price": 720, "sku_code": "RG-TRT-004"}'::jsonb,true,12),
('product','RG-TRT-005','{"name": "Centella Soothing Essence 100ml", "brand": "AloePure", "category": "Treat", "price": 480, "sku_code": "RG-TRT-005"}'::jsonb,true,13),
('product','RG-TRT-006','{"name": "Peptide Firming Eye Cream 15ml", "brand": "AgeSoft", "category": "Treat", "price": 790, "sku_code": "RG-TRT-006"}'::jsonb,true,14),
('product','RG-TRT-007','{"name": "AHA BHA Clarifying Toner 150ml", "brand": "UrbanSkin", "category": "Treat", "price": 520, "sku_code": "RG-TRT-007"}'::jsonb,true,15),
('product','RG-TRT-008','{"name": "Snail Mucin Repair Cream 50ml", "brand": "SilkDerm", "category": "Treat", "price": 650, "sku_code": "RG-TRT-008"}'::jsonb,true,16),
('product','RG-TRT-009','{"name": "Ceramide Barrier Balm 40ml", "brand": "BarrierCare", "category": "Treat", "price": 740, "sku_code": "RG-TRT-009"}'::jsonb,true,17),
('product','RG-PRT-001','{"name": "Daily Soft Sunscreen SPF50 50ml", "brand": "SunSoft", "category": "Protect", "price": 590, "sku_code": "RG-PRT-001"}'::jsonb,true,18),
('product','RG-PRT-002','{"name": "Tone-Up UV Essence SPF50+ 40ml", "brand": "SunSoft", "category": "Protect", "price": 690, "sku_code": "RG-PRT-002"}'::jsonb,true,19),
('product','RG-PRT-003','{"name": "Matte Airy Sunscreen SPF50 45ml", "brand": "UrbanSkin", "category": "Protect", "price": 549, "sku_code": "RG-PRT-003"}'::jsonb,true,20),
('product','RG-PRT-004','{"name": "Kids Mineral Sunscreen SPF40 80ml", "brand": "SunSoft", "category": "Protect", "price": 420, "sku_code": "RG-PRT-004"}'::jsonb,true,21),
('product','RG-PRT-005','{"name": "Overnight Sleeping Mask 80ml", "brand": "AquaLayer", "category": "Protect", "price": 490, "sku_code": "RG-PRT-005"}'::jsonb,true,22),
('product','RG-PRT-006','{"name": "Antioxidant Day Cream SPF30 50ml", "brand": "GlowLab", "category": "Protect", "price": 780, "sku_code": "RG-PRT-006"}'::jsonb,true,23),
('product','RG-PRT-007','{"name": "Lip Balm SPF15 Duo Pack", "brand": "SilkDerm", "category": "Protect", "price": 249, "sku_code": "RG-PRT-007"}'::jsonb,true,24),
('product','RG-PRT-008','{"name": "Pollution Shield Mist 100ml", "brand": "UrbanSkin", "category": "Protect", "price": 399, "sku_code": "RG-PRT-008"}'::jsonb,true,25),
('product','RG-BDY-001','{"name": "Rice Milk Body Wash 400ml", "brand": "RiceGlow", "category": "Body", "price": 289, "sku_code": "RG-BDY-001"}'::jsonb,true,26),
('product','RG-BDY-002','{"name": "Shea Soft Body Lotion 250ml", "brand": "SilkDerm", "category": "Body", "price": 349, "sku_code": "RG-BDY-002"}'::jsonb,true,27),
('product','RG-BDY-003','{"name": "Cooling Aloe Body Gel 300ml", "brand": "AloePure", "category": "Body", "price": 259, "sku_code": "RG-BDY-003"}'::jsonb,true,28),
('product','RG-BDY-004','{"name": "Exfoliating Body Scrub 200g", "brand": "UrbanSkin", "category": "Body", "price": 390, "sku_code": "RG-BDY-004"}'::jsonb,true,29),
('product','RG-BDY-005','{"name": "Hand Cream Soft Petal 50ml", "brand": "SilkDerm", "category": "Body", "price": 179, "sku_code": "RG-BDY-005"}'::jsonb,true,30),
('product','RG-BDY-006','{"name": "Hair & Scalp Clarifying Shampoo 300ml", "brand": "MatchaLab", "category": "Body", "price": 420, "sku_code": "RG-BDY-006"}'::jsonb,true,31),
('product','RG-BDY-007','{"name": "Nourishing Conditioner 300ml", "brand": "MatchaLab", "category": "Body", "price": 420, "sku_code": "RG-BDY-007"}'::jsonb,true,32),
('product','RG-BDY-008','{"name": "Deodorant Fresh Citrus 50ml", "brand": "UrbanSkin", "category": "Body", "price": 199, "sku_code": "RG-BDY-008"}'::jsonb,true,33),
('product','RG-SET-001','{"name": "Rice Glow Starter Kit", "brand": "RiceGlow", "category": "Sets", "price": 1290, "sku_code": "RG-SET-001"}'::jsonb,true,34),
('product','RG-SET-002','{"name": "Brightening Serum Duo Set", "brand": "GlowLab", "category": "Sets", "price": 1490, "sku_code": "RG-SET-002"}'::jsonb,true,35),
('product','RG-SET-003','{"name": "Barrier Repair Essentials Trio", "brand": "BarrierCare", "category": "Sets", "price": 1890, "sku_code": "RG-SET-003"}'::jsonb,true,36),
('product','RG-SET-004','{"name": "Daily Sun Care Gift Box", "brand": "SunSoft", "category": "Sets", "price": 1590, "sku_code": "RG-SET-004"}'::jsonb,true,37),
('product','RG-SET-005','{"name": "Travel Mini Cleanse Treat Pack", "brand": "RiceGlow", "category": "Sets", "price": 990, "sku_code": "RG-SET-005"}'::jsonb,true,38),
('product','RG-SET-006','{"name": "Age Soft Night Ritual Set", "brand": "AgeSoft", "category": "Sets", "price": 2190, "sku_code": "RG-SET-006"}'::jsonb,true,39),
('product','RG-SET-007','{"name": "Full Glow Discovery Collection", "brand": "GlowLab", "category": "Sets", "price": 2490, "sku_code": "RG-SET-007"}'::jsonb,true,40),
('product','RG-SET-008','{"name": "Body Spa Soft Care Bundle", "brand": "SilkDerm", "category": "Sets", "price": 1190, "sku_code": "RG-SET-008"}'::jsonb,true,41)
ON CONFLICT (kind,code) DO UPDATE SET payload=EXCLUDED.payload, updated_at=now();
INSERT INTO public.custom_internal_demo_config (kind,code,payload,is_active,sort_order) VALUES
('archetype','whale','{"purchase_propensity": 0.35, "visit_propensity": 0.5, "redeem_propensity": 0.12, "survey_propensity": 0.08, "spin_propensity": 0.04, "mission_propensity": 0.2, "basket_mean": 1800, "decay_days": 400, "weight": 0.08}'::jsonb,true,1),
('archetype','regular','{"purchase_propensity": 0.12, "visit_propensity": 0.35, "redeem_propensity": 0.06, "survey_propensity": 0.05, "spin_propensity": 0.02, "mission_propensity": 0.12, "basket_mean": 750, "decay_days": 200, "weight": 0.35}'::jsonb,true,2),
('archetype','occasional','{"purchase_propensity": 0.05, "visit_propensity": 0.15, "redeem_propensity": 0.03, "survey_propensity": 0.025, "spin_propensity": 0.01, "mission_propensity": 0.06, "basket_mean": 550, "decay_days": 120, "weight": 0.3}'::jsonb,true,3),
('archetype','one_timer','{"purchase_propensity": 0.02, "visit_propensity": 0.08, "redeem_propensity": 0.01, "survey_propensity": 0.02, "spin_propensity": 0.005, "mission_propensity": 0.03, "basket_mean": 450, "decay_days": 45, "weight": 0.17}'::jsonb,true,4),
('archetype','lapsed_winback','{"purchase_propensity": 0.03, "visit_propensity": 0.1, "redeem_propensity": 0.02, "survey_propensity": 0.03, "spin_propensity": 0.01, "mission_propensity": 0.05, "basket_mean": 650, "decay_days": 90, "weight": 0.1, "winback_after_days": 60}'::jsonb,true,5)
ON CONFLICT (kind,code) DO UPDATE SET payload=EXCLUDED.payload, updated_at=now();
INSERT INTO public.custom_internal_demo_config (kind,code,payload,is_active,sort_order) VALUES
('campaign','songkran_glow','{"label": "Songkran Glow Sale", "start_offset_days": -170, "end_offset_days": -155, "propensity_boost": 1.35}'::jsonb,true,1),
('campaign','payday_may','{"label": "Payday Special", "start_offset_days": -140, "end_offset_days": -135, "propensity_boost": 1.2}'::jsonb,true,2),
('campaign','midyear_glow','{"label": "Mid-Year Glow Fest", "start_offset_days": -100, "end_offset_days": -85, "propensity_boost": 1.4}'::jsonb,true,3),
('campaign','mothers_day','{"label": "Mother''s Day Soft Skin", "start_offset_days": -75, "end_offset_days": -68, "propensity_boost": 1.25}'::jsonb,true,4),
('campaign','payday_jul','{"label": "Payday Special", "start_offset_days": -50, "end_offset_days": -45, "propensity_boost": 1.2}'::jsonb,true,5),
('campaign','eleven_eleven','{"label": "11.11 Mega Glow", "start_offset_days": -30, "end_offset_days": -25, "propensity_boost": 1.5}'::jsonb,true,6),
('campaign','year_end','{"label": "Year-End Glow Gift", "start_offset_days": -10, "end_offset_days": 5, "propensity_boost": 1.3}'::jsonb,true,7)
ON CONFLICT (kind,code) DO UPDATE SET payload=EXCLUDED.payload, updated_at=now();
INSERT INTO public.custom_internal_demo_config (kind,code,payload,is_active,sort_order) VALUES
('settings','default','{"merchant_id": "fae172a5-de90-440e-a766-db6a5982cc9b", "merchant_code": "rocket-demo", "seed_tag": "SEED-RKT", "target_members": 2500, "seed_days": 180, "daily_new_signups_mean": 8, "points_per_thb": 0.1, "mode_default": "backfill"}'::jsonb,true,0)
ON CONFLICT (kind,code) DO UPDATE SET payload=EXCLUDED.payload, updated_at=now();
