#!/usr/bin/env python3
"""Generate phase2.sql + verify_phase2.sql for the Thai address master fix.

Official sources (both in ./data):
  - DOPA ccaatt.xlsx (directory as of 1 Sep 2023), archived copy 2026-08-07:
    web.archive.org/web/20260807080618id_/http://stat.bora.dopa.go.th/dload/ccaatt.xlsx
  - Thailand Post nationwide postcode poster (2018):
    file.thailandpost.com/upload/content/_5e856abf6c77a.pdf
Rule: change a value only where the official source agrees with the community
reference (kongvut @ 7d689e4), except where noted.
"""
import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"

dopa = json.loads((DATA / "dopa_ccaatt.json").read_text(encoding="utf-8"))
ref = {str(r["id"]): r for r in json.loads((DATA / "ref_sub_district.json").read_text(encoding="utf-8"))}

strip = lambda n: re.sub(r"^(ต\.|แขวง|อ\.|เขต)", "", n or "")
q = lambda s: "'" + s.replace("'", "''") + "'"

live_sub, live_dist = {}, {}
for line in (DATA / "live_phase2_rows.tsv").read_text(encoding="utf-8").splitlines():
    f = line.split("\t")
    if f[0].startswith("D"):
        live_dist[f[0][1:]] = {"th": f[1], "en": f[2]}
    else:
        live_sub[f[0]] = {"th": f[1], "en": f[2], "zip": f[3], "d": f[4]}

INSERTS = ["410116", "500108", "830104"]
INSERT_ZIP = {"410116": 41000, "500108": 50200, "830104": 83000}

# Old code -> code that officially holds the name the member saw in the dropdown.
REPOINT = {
    "110402": "110401",
    "141108": "141109",
    "141109": "141108",
    "410111": "410116",
    "461803": "461804",
    "461804": "461805",
    "461805": "461803",
    "481202": "481203",
    "481203": "481202",
    "500109": "500108",
}

DELETE = ["200409", "920221", "920222", "920414"]

# Thailand Post gives one postcode for the whole tambon and it matches the reference.
POSTCODE = {"240409": 24130, "551502": 55130, "901604": 90115, "920106": 92000}

# Name changes beyond spelling where DOPA and the reference romanise differently; use DOPA.
EN_FROM_DOPA = {"342504", "441106"}

DISTRICTS = ["3801", "4906", "9310", "9508"]

renames = []
for sid, lv in sorted(live_sub.items()):
    d = dopa.get(sid)
    if sid in DELETE or not d or d["gone"]:
        continue
    r = ref[sid]["name"]
    new_th = "ต." + d["th"]
    th_changes = strip(lv["th"]) != d["th"]
    if th_changes and d["th"] != r["th"]:
        raise SystemExit(f"{sid}: DOPA and reference disagree on Thai name")
    if lv["en"] == "0" or sid in EN_FROM_DOPA:
        new_en = d["en"]
    elif d["en"] == r["en"] and d["en"] != lv["en"]:
        new_en = d["en"]
    else:
        new_en = lv["en"]
    if th_changes or new_en != lv["en"]:
        renames.append((sid, lv["th"], new_th, lv["en"], new_en))

dist_renames = []
for did in DISTRICTS:
    d = dopa[did]
    dist_renames.append((did, live_dist[did]["th"], "อ." + d["th"], live_dist[did]["en"], d["en"]))

sub_touched = sorted(set(INSERTS) | set(REPOINT) | set(REPOINT.values()) | {r[0] for r in renames} | set(POSTCODE) | set(DELETE))
in_list = lambda ids: "(" + ", ".join(q(i) for i in ids) + ")"

L = []
L.append("-- Generated by scripts/gen_phase2.py — fix_thai_address_master_phase2")
L.append("-- Sources: DOPA ccaatt (1 Sep 2023); Thailand Post postcode poster (2018)")
L.append("")
L.append("-- Backup (RLS enabled, no policies)")
L.append("CREATE TABLE public._bak_20261002_p2_address_th_subdistrict AS")
L.append(f"SELECT * FROM public.address_th_subdistrict WHERE id IN {in_list(sub_touched)};")
L.append("ALTER TABLE public._bak_20261002_p2_address_th_subdistrict ENABLE ROW LEVEL SECURITY;")
L.append("CREATE TABLE public._bak_20261002_p2_address_th_district AS")
L.append(f"SELECT * FROM public.address_th_district WHERE id IN {in_list(DISTRICTS)};")
L.append("ALTER TABLE public._bak_20261002_p2_address_th_district ENABLE ROW LEVEL SECURITY;")
L.append("CREATE TABLE public._bak_20261002_p2_user_address AS")
L.append("SELECT id, province_code, district_code, subdistrict_code, city, district, subdistrict")
L.append("FROM public.user_address")
L.append(f"WHERE subdistrict_code IN {in_list(sub_touched)}")
L.append(f"   OR district_code IN {in_list(DISTRICTS)};")
L.append("ALTER TABLE public._bak_20261002_p2_user_address ENABLE ROW LEVEL SECURITY;")
L.append("")

L.append(f"-- Step 1: insert {len(INSERTS)} subdistricts that DOPA lists and we lack")
L.append("INSERT INTO public.address_th_subdistrict (id, zip_code, subdistrict_name_th, subdistrict_name_en, district_id, district_name_th, district_name_en)")
L.append("SELECT v.id, v.zip_code, v.name_th, v.name_en, d.id::bigint, d.district_name_th, d.district_name_en")
L.append("FROM (VALUES")
vals = []
for sid in INSERTS:
    d = dopa[sid]
    vals.append(f"  ({q(sid)}, {INSERT_ZIP[sid]}, {q('ต.' + d['th'])}, {q(d['en'])}, {q(sid[:4])})")
L.append(",\n".join(vals))
L.append(") AS v(id, zip_code, name_th, name_en, district_code)")
L.append("JOIN public.address_th_district AS d ON d.id = v.district_code;")
L.append("")

L.append("-- Step 2: re-point saved addresses to the code that officially holds the name the member picked")
L.append("UPDATE public.user_address AS ua")
L.append("SET subdistrict_code = m.new_code,")
L.append("    subdistrict = CASE WHEN ua.subdistrict = m.old_code THEN m.new_code ELSE ua.subdistrict END")
L.append("FROM (VALUES")
L.append(",\n".join(f"  ({q(o)}, {q(n)})" for o, n in sorted(REPOINT.items())))
L.append(") AS m(old_code, new_code)")
L.append("WHERE ua.subdistrict_code = m.old_code;")
L.append("")

L.append(f"-- Step 3: correct {len(renames)} subdistrict names to DOPA")
L.append("CREATE TEMP TABLE _p2_sub_rename (id text PRIMARY KEY, old_th text, new_th text, new_en text) ON COMMIT DROP;")
L.append("INSERT INTO _p2_sub_rename VALUES")
L.append(",\n".join(f"  ({q(i)}, {q(ot)}, {q(nt)}, {q(ne)})" for i, ot, nt, oe, ne in renames))
L.append(";")
L.append("UPDATE public.address_th_subdistrict AS s")
L.append("SET subdistrict_name_th = r.new_th, subdistrict_name_en = r.new_en")
L.append("FROM _p2_sub_rename AS r WHERE s.id = r.id;")
L.append("UPDATE public.user_address AS ua")
L.append("SET subdistrict = r.new_th")
L.append("FROM _p2_sub_rename AS r")
L.append("WHERE ua.subdistrict_code = r.id AND ua.subdistrict = r.old_th AND r.old_th <> r.new_th;")
L.append("")

L.append(f"-- Step 4: {len(POSTCODE)} postcodes where Thailand Post agrees with the reference")
for sid, z in sorted(POSTCODE.items()):
    L.append(f"UPDATE public.address_th_subdistrict SET zip_code = {z} WHERE id = {q(sid)};")
L.append("")

L.append(f"-- Step 5: correct {len(dist_renames)} district names to DOPA and refresh child rows")
for did, ot, nt, oe, ne in dist_renames:
    L.append(f"UPDATE public.address_th_district SET district_name_th = {q(nt)}, district_name_en = {q(ne)} WHERE id = {q(did)};")
    if ot != nt:
        L.append(f"UPDATE public.user_address SET district = {q(nt)} WHERE district_code = {q(did)} AND district = {q(ot)};")
L.append("UPDATE public.address_th_subdistrict AS s")
L.append("SET district_name_th = d.district_name_th, district_name_en = d.district_name_en")
L.append("FROM public.address_th_district AS d")
L.append(f"WHERE s.district_id = d.id::bigint AND d.id IN {in_list(DISTRICTS)};")
L.append("")

L.append(f"-- Step 6: delete {len(DELETE)} codes DOPA does not list (abort if any saved address uses them)")
L.append("DO $$")
L.append("DECLARE n int;")
L.append("BEGIN")
L.append(f"  SELECT count(*) INTO n FROM public.user_address WHERE subdistrict_code IN {in_list(DELETE)};")
L.append("  IF n > 0 THEN RAISE EXCEPTION 'user_address still references deleted codes: %', n; END IF;")
L.append("END $$;")
L.append(f"DELETE FROM public.address_th_subdistrict WHERE id IN {in_list(DELETE)};")
L.append("")

dopa_sub_ids = sorted(k for k, v in dopa.items() if len(k) == 6 and k.isdigit() and not v["gone"])
ids_md5 = hashlib.md5(",".join(dopa_sub_ids).encode()).hexdigest()
L.append("-- Step 7: subdistrict codes must now equal DOPA's active list exactly")
L.append("DO $$")
L.append("DECLARE n int; h text;")
L.append("BEGIN")
L.append("  SELECT count(*), md5(string_agg(id, ',' ORDER BY id)) INTO n, h FROM public.address_th_subdistrict;")
L.append(f"  IF n <> {len(dopa_sub_ids)} OR h <> '{ids_md5}' THEN")
L.append(f"    RAISE EXCEPTION 'subdistrict codes differ from DOPA: count % (expected {len(dopa_sub_ids)}), md5 %', n, h;")
L.append("  END IF;")
L.append("END $$;")
(ROOT / "phase2.sql").write_text("\n".join(L) + "\n", encoding="utf-8")

V = []
V.append(f"SELECT 'count_eq_dopa' AS check_name, '{len(dopa_sub_ids)}' AS expected, count(*)::text AS actual FROM public.address_th_subdistrict")
V.append(f"UNION ALL SELECT 'ids_md5_eq_dopa', '{ids_md5}', md5(string_agg(id, ',' ORDER BY id)) FROM public.address_th_subdistrict")
V.append("UNION ALL SELECT 'en_zero', '0', count(*)::text FROM public.address_th_subdistrict WHERE subdistrict_name_en = '0'")
V.append("UNION ALL SELECT 'zip_zero_or_null', '0', count(*)::text FROM public.address_th_subdistrict WHERE zip_code IS NULL OR zip_code = 0")
V.append("UNION ALL SELECT 'dup_name_in_district', '0', count(*)::text FROM (SELECT district_id, subdistrict_name_th FROM public.address_th_subdistrict GROUP BY 1, 2 HAVING count(*) > 1) z")
V.append(f"UNION ALL SELECT 'ua_on_deleted', '0', count(*)::text FROM public.user_address WHERE subdistrict_code IN {in_list(DELETE)}")
V.append("UNION ALL SELECT 'renamed_rows_match', " + f"'{len(renames)}', count(*)::text FROM public.address_th_subdistrict s JOIN (VALUES "
         + ", ".join(f"({q(i)}, {q(nt)}, {q(ne)})" for i, ot, nt, oe, ne in renames)
         + ") v(id, th, en) ON s.id = v.id AND s.subdistrict_name_th = v.th AND s.subdistrict_name_en = v.en")
V.append("UNION ALL SELECT 'chiang_mai_suthep', '500108 ต.สุเทพ 50200', (SELECT id || ' ' || subdistrict_name_th || ' ' || zip_code FROM public.address_th_subdistrict WHERE id = '500108')")
V.append("UNION ALL SELECT 'district_3801', 'อ.เมืองบึงกาฬ', (SELECT district_name_th FROM public.address_th_district WHERE id = '3801');")
(ROOT / "verify_phase2.sql").write_text("\n".join(V) + "\n", encoding="utf-8")

print(f"inserts {len(INSERTS)}, repoint codes {len(REPOINT)}, renames {len(renames)}, postcodes {len(POSTCODE)}, districts {len(dist_renames)}, deletes {len(DELETE)}")
print(f"expected subdistricts {len(dopa_sub_ids)} md5 {ids_md5}")
for r in renames:
    print(" ", r)
