-- Product Feature Catalog Thai localize 2026-08-12
-- run_id: b7e4a91c-2d8f-4c3a-a1e0-202608120001
-- Craft: localize per Writing Principles TRANSLATION_PHILOSOPHY + TRANSLATION_PRINCIPLES + slide §6

BEGIN;

WITH th(feature_key, name_th, summary_th) AS (
  VALUES
  -- Loyalty / foundation
  ('platform.signup.login_methods',
   'เข้าสู่ระบบด้วย LINE หรือ OTP ทางโทรศัพท์',
   'สมาชิกเข้าสู่ระบบด้วย LINE, OTP ทางโทรศัพท์ หรือทั้งสองแบบ — คุณเลือกได้ว่าแบรนด์จะเปิดช่องทางใด'),
  ('platform.signup.complete_profile',
   'กรอกโปรไฟล์หลังสมัคร',
   'หลังล็อกอิน สมาชิกกรอกข้อมูลที่คุณต้องการ (ชื่อ วันเกิด ฯลฯ) ก่อนเข้าใช้งานแอป'),
  ('platform.signup.on_your_website',
   'สมัครสมาชิกบนเว็บไซต์ของคุณ',
   'ฝัง flow สมัคร/ล็อกอินของ Rocket บนเว็บไซต์หรือร้านออนไลน์ของคุณได้ โดยสมาชิกไม่ต้องออกจากเว็บคุณ'),
  ('platform.experience.display_settings',
   'จัดหน้าแรกและเลย์เอาต์หน้าจอ',
   'จัดองค์ประกอบที่สมาชิกเห็นบนหน้าแรก — แบนเนอร์ สรุปคะแนน ความคืบหน้า Tier ของรางวัลเด่น เมนู — โดยไม่ต้องพึ่งงาน engineer'),
  ('platform.governance.pdpa_consent',
   'ความยินยอมความเป็นส่วนตัว (PDPA)',
   'สมาชิกยอมรับเงื่อนไขความเป็นส่วนตัวตอนสมัคร และคุณเก็บหลักฐานความยินยอมนั้นไว้'),
  ('platform.governance.admin_shell',
   'ผู้ใช้แอดมินและสิทธิ์การใช้งาน',
   'เชิญทีมเข้าแอดมิน และกำหนดว่าแต่ละ role ดูหรือแก้ได้อะไร'),
  ('platform.governance.translation',
   'หลายภาษา',
   'แสดงของรางวัล ฟอร์ม Tier และข้อความในแอปตามภาษาของสมาชิก (เช่น ไทยและอังกฤษ)'),

  -- Currency
  ('loyalty.currency.points',
   'ยอดคะแนน (Points)',
   'สมาชิกสะสมคะแนนใน wallet ที่เห็นได้ชัด และนำไปใช้แลกของรางวัลหรือส่วนลดได้ภายหลัง'),
  ('loyalty.currency.tickets',
   'Tickets (สกุลเงินที่สอง)',
   'ยอดสำรองสำหรับแคมเปญพิเศษ เช่น ตั๋วจับฉลาก แยกจากคะแนนปกติ'),
  ('loyalty.currency.expiry',
   'วันหมดอายุของคะแนน',
   'คะแนนที่ไม่ได้ใช้สามารถหมดอายุตามระยะเวลาที่คุณตั้ง เพื่อไม่ให้ยอดเก่าค้างถาวร'),
  ('loyalty.currency.earn_rate_basic',
   'อัตราการได้คะแนน — พื้นฐาน',
   'ตั้งกฎง่าย ๆ ว่าการใช้จ่ายแปลงเป็นคะแนนอย่างไร'),
  ('loyalty.currency.earn_rate_advanced',
   'อัตราการได้คะแนน — ขั้นสูง',
   'ตั้งอัตราได้คะแนนต่างกันตามช่องทาง (และมิติอื่นที่เกี่ยวข้อง) ไม่ใช่เรทเดียวทั้งระบบ'),
  ('loyalty.currency.multipliers',
   'ตัวคูณคะแนนโบนัส',
   'คูณคะแนนสำหรับสินค้าหรือหมวดที่เลือก เช่น double points สินค้าสกินแคร์'),

  -- Earn
  ('loyalty.earn.channel_page',
   'ตั้งค่าหน้า Earn',
   'เลือกว่าช่องทางใดจะโชว์บนหน้า Earn ของสมาชิก (ซื้อ Mission วันเกิด ฯลฯ)'),
  ('loyalty.earn.purchase_sync',
   'ได้คะแนนจากการซิงค์การซื้อ',
   'ระบบเติมคะแนนอัตโนมัติเมื่อมีการซื้อจาก POS หรือร้านออนไลน์ของคุณ'),
  ('loyalty.earn.marketplace',
   'ได้คะแนนจากออเดอร์ marketplace',
   'สมาชิกได้คะแนนจาก Shopee, Lazada, TikTok Shop (หรือแพลตฟอร์มใกล้เคียง) โดยเคลมหรือจับคู่คำสั่งซื้อ'),
  ('loyalty.earn.qr_or_code',
   'ได้คะแนนจากสแกน QR / รหัส',
   'สมาชิกสแกน QR หรือกรอกรหัสบนสินค้า/ใบเสร็จ/โปสเตอร์เพื่อรับคะแนน'),
  ('loyalty.earn.receipt_upload',
   'ได้คะแนนจากการอัปโหลดใบเสร็จ',
   'สมาชิกถ่ายใบเสร็จกระดาษ หลังตรวจ/อนุมัติด้วย OCR แล้วจึงได้คะแนน'),
  ('loyalty.earn.receipt_advanced',
   'ตรวจใบเสร็จขั้นสูง',
   'เร่งการได้คะแนนจากใบเสร็จด้วยการอนุมัติอัตโนมัติ และ/หรือให้คะแนนตามรายการสินค้าในใบเสร็จ'),
  ('loyalty.earn.activity_proof',
   'ได้คะแนนจากหลักฐานกิจกรรม',
   'สมาชิกอัปโหลดรูปเป็นหลักฐานการทำกิจกรรมที่ไม่ใช่การซื้อ แล้วได้คะแนนหลังผ่านการตรวจ'),
  ('loyalty.earn.manual_adjust',
   'ปรับคะแนนด้วยมือ (Front Line)',
   'พนักงานเติมหรือแก้คะแนนให้สมาชิกใน Front Line ได้ (ชดเชยบริการ ความผิดพลาด การย้ายข้อมูล)'),
  ('loyalty.earn.openapi',
   'ให้คะแนนผ่าน Open API',
   'ระบบของคุณเรียก API ของ Rocket เพื่อให้คะแนนได้เอง (พาร์ทเนอร์ แอปคัสตอม)'),

  -- Reward / burn
  ('loyalty.reward.catalog',
   'แคตตาล็อกของรางวัลและการแลก',
   'สมาชิกเลือกดูและแลกของรางวัลด้วยคะแนน'),
  ('loyalty.reward.dynamic_pricing',
   'ราคาคะแนนของรางวัลแบบไดนามิก',
   'ของรางวัลชิ้นเดียวกันอาจใช้คะแนนต่างกันตามสมาชิก'),
  ('loyalty.reward.eligibility',
   'ตัวกรองสิทธิ์แลกของรางวัล',
   'ควบคุมว่าใครเห็นหรือแลกของรางวัลได้ (Tier, persona, ช่วงเวลา ฯลฯ)'),
  ('loyalty.reward.groups_limits',
   'กลุ่มของรางวัลและโควต้าร่วม',
   'จำกัดการเลือกระหว่างชุดของรางวัลที่เกี่ยวข้องกัน'),
  ('loyalty.reward.promo_codes',
   'ส่งมอบด้วยโปรโมโค้ด',
   'ออกโปรโม/คูปองโค้ดแบบไม่ซ้ำเมื่อมีการแลก'),
  ('loyalty.reward.admin_push_claim',
   'แอดมินส่งของรางวัลและลิงก์/QR เคลม',
   'ส่งของรางวัลแบบ 1:1 หรือแจกผ่านลิงก์เคลม/QR'),
  ('loyalty.burn.rate_default',
   'อัตรา burn — ค่าเริ่มต้นร้านค้า',
   'แปลงคะแนนเป็นส่วนลดเงินตอนชำระเงินโดยตรง (ไม่ใช่ของรางวัลในแคตตาล็อก)'),
  ('loyalty.burn.rate_per_tier',
   'อัตรา burn — ปรับตาม Tier',
   'ตั้งอัตราแลกคะแนนเป็นส่วนลดต่างกันตาม Tier หรือปิด burn ในบาง Tier'),

  -- Tier
  ('loyalty.tier.ladder',
   'บันได Tier และสิทธิประโยชน์',
   'กำหนดระดับสมาชิก พร้อมสิทธิที่แสดงผลและลำดับการเลื่อนขั้น'),
  ('loyalty.tier.upgrade_conditions',
   'เงื่อนไขเลื่อน Tier',
   'ตั้งว่าต้องสะสมเท่าไรจึงเลื่อนขึ้น Tier ถัดไป (เช่น คะแนนหรือยอดใช้จ่าย)'),
  ('loyalty.tier.maintain_mode',
   'โหมดรักษา / ยืนยันสิทธิ์ Tier',
   'เลือกว่าสมาชิกที่ได้ Tier แล้วจะคงถาวร หรือต้องยืนยันสิทธิ์ใหม่ทุกช่วงเวลา'),
  ('loyalty.tier.evaluation_windows',
   'ช่วงเวลาประเมิน Tier',
   'เลือกหน้าต่างเวลาที่ใช้วัดความคืบหน้า Tier (ปีปฏิทินหรือ rolling months) และจังหวะที่อัปเกรดมีผล'),
  ('loyalty.tier.per_tier_earn_rate',
   'อัตราได้คะแนนตาม Tier',
   'ให้อัตราได้คะแนนต่างกันตาม Tier ของสมาชิก'),
  ('loyalty.tier.persona_scope',
   'บันได Tier ตาม persona',
   'ใช้บันได Tier คนละชุดตามกลุ่ม persona / user type'),

  -- Campaign
  ('loyalty.campaign.mission_standard',
   'Mission — แบบมาตรฐาน',
   'Mission ที่สมาชิกทำหลายเป้าหมาย (ลำดับใดก็ได้) เพื่อรับของรางวัล'),
  ('loyalty.campaign.mission_milestone',
   'Mission — แบบ milestone / ทีละขั้น',
   'Mission ที่มีขั้นเรียงลำดับ — ทำขั้น 1 เสร็จก่อนขั้น 2 จึงปลดล็อก'),
  ('loyalty.campaign.referral',
   'Referral (แนะนำเพื่อน)',
   'เชิญเพื่อนด้วยรหัส เมื่อครบเงื่อนไขทั้งสองฝ่ายรับของรางวัลได้'),
  ('loyalty.campaign.checkin',
   'Check-in',
   'สมาชิกเช็คอินรายวัน/รายสัปดาห์เพื่อสะสม streak และรับของรางวัล'),
  ('loyalty.campaign.spin_wheel',
   'วงล้อสุ่ม (Spin wheel)',
   'สมาชิกใช้คะแนนหรือ tickets หมุนวงล้อลุ้นรางวัลแบบสุ่ม'),
  ('loyalty.campaign.lucky_draw',
   'จับฉลากจำนวนมาก (Lucky draw)',
   'การจับฉลากที่เข้าด้วยสกุลเงิน แล้วคัดผู้ชนะแบบออฟไลน์'),

  -- Forms / lifecycle
  ('loyalty.forms.profile_fields',
   'ตั้งค่าฟิลด์โปรไฟล์',
   'กำหนดฟิลด์โปรไฟล์มาตรฐาน (อีเมล โทรศัพท์ ชื่อ ที่อยู่ ฯลฯ)'),
  ('loyalty.forms.custom_fields',
   'ฟิลด์กำหนดเอง',
   'ฟิลด์ที่ร้านค้าสร้างเอง นอกเหนือชุดโปรไฟล์มาตรฐาน'),
  ('loyalty.forms.signup_form',
   'ฟอร์มสมัคร / กรอกโปรไฟล์แบบกำหนดเอง',
   'เลือกว่าจะถามข้อมูลโปรไฟล์ข้อใดตอนสมัครหรือตอนกรอกโปรไฟล์ให้ครบ'),
  ('loyalty.forms.surveys',
   'ฟอร์มแบบสำรวจ',
   'ฟอร์มแบบ survey สำหรับเก็บฟีดแบ็กและเสริมข้อมูลสมาชิก'),
  ('loyalty.lifecycle.signup_outcomes',
   'Automation เมื่อสมัครสมาชิก',
   'ให้คะแนน ของรางวัล หรือแท็กอัตโนมัติเมื่อสมาชิกสมัครครบ'),
  ('loyalty.lifecycle.birthday',
   'Automation วันเกิด',
   'ทริกเกอร์ผลลัพธ์ loyalty อัตโนมัติช่วงวันเกิดสมาชิก'),
  ('loyalty.lifecycle.anniversary',
   'Automation วันครบรอบสมาชิก',
   'ทริกเกอร์ผลลัพธ์ loyalty อัตโนมัติในวันครบรอบการเป็นสมาชิก'),
  ('loyalty.lifecycle.tier_change',
   'Automation เมื่อเปลี่ยน Tier',
   'ทริกเกอร์ผลลัพธ์อัตโนมัติเมื่อสมาชิกเลื่อนหรือลด Tier'),

  -- Persona / store / frontline / analytics / ops
  ('loyalty.persona.tags_personas',
   'แท็กและ persona',
   'จัดกลุ่มสมาชิกเพื่อใช้กับสิทธิ์ automation และการรายงาน'),
  ('loyalty.persona.user_types',
   'ประเภทผู้ใช้ (User types)',
   'ประเภทผู้ใช้เชิงโครงสร้าง (เช่น ผู้ซื้อ/ผู้ขาย) สำหรับกฎและบันได Tier'),
  ('loyalty.persona.entitlements',
   'สิทธิพิเศษตาม persona',
   'ให้ persona เข้าถึงหรือได้สิทธิเพิ่มนอกเหนือแท็กทั่วไป'),
  ('loyalty.store.master',
   'ข้อมูลร้าน (Store master)',
   'ดูแลสาขาที่ใช้กับการได้คะแนน การแลก และการรายงาน'),
  ('loyalty.store.attributes',
   'จัดหมวดแอตทริบิวต์ร้าน',
   'จัดประเภทร้านตามช่องทาง/ภูมิภาค/คุณลักษณะธุรกิจเพื่อใช้กับกฎ'),
  ('loyalty.frontline.customer_360',
   'Customer 360 / Front Line',
   'มุมมอง Customer 360 สำหรับบริการ: สถานะ ความคืบหน้า Tier ประวัติ และบริบทสมาชิก'),
  ('loyalty.frontline.assisted_actions',
   'การช่วยเหลือใน Front Line',
   'พนักงานช่วยสมาชิกใน Front Line ได้: ปรับคะแนน ส่งของรางวัล ทำเครื่องหมายใช้แล้ว'),
  ('loyalty.analytics.reports',
   'รายงาน analytics ของ loyalty',
   'รายงานกว่า 30 ฉบับครอบคลุมการซื้อ คะแนน การแลก Campaign และสมาชิก — ให้ทีมเห็นผลโปรแกรมได้'),
  ('loyalty.analytics.rfm',
   'คะแนน RFM',
   'ให้คะแนนสมาชิกจากความถี่ ความใกล้ และมูลค่าการซื้อ เพื่อใช้กำหนดเป้า'),
  ('loyalty.analytics.funnel',
   'ขั้น Funnel',
   'กำหนดขั้นใน journey และรายงาน conversion'),
  ('loyalty.ops.customer_import_export',
   'นำเข้า / ส่งออกสมาชิก',
   'ย้ายหรือส่งออกโปรไฟล์สมาชิกเป็นชุด'),
  ('loyalty.ops.bulk_currency_import',
   'นำเข้าคะแนน/ตั๋วเป็นชุด',
   'โหลดคะแนนหรือ tickets จำนวนมากสำหรับย้ายระบบหรือแคมเปญ'),
  ('loyalty.storefront.shopify_widget',
   'Widget loyalty บน Shopify',
   'แสดงสถานะ loyalty ของสมาชิกบนหน้าร้าน Shopify'),
  ('loyalty.storefront.shopify_burn',
   'ใช้คะแนนเป็นส่วนลดบน Shopify',
   'ใช้ burn คะแนนเป็นส่วนลดใน journey checkout ของ Shopify'),
  ('loyalty.stored_value.cards',
   'บัตรมูลค่าเก็บเงิน (Stored value)',
   'บัตรแบบเติมเงินที่มียอดเทียบเท่าเงินสด'),
  ('loyalty.stored_value.store_credit',
   'Store credit',
   'ยอดเครดิตโปรโม/ร้าน ที่แยกจากคะแนน'),
  ('loyalty.event_promo.engine',
   'เอนจินโปรโมชันอีเวนต์',
   'ของแถม/ส่วนลดเฉพาะอีเวนต์ และการจับคู่สิทธิ์เคลม'),
  ('loyalty.integrations.open_api',
   'Loyalty Open API',
   'API สำหรับพาร์ทเนอร์ด้านผู้ใช้ wallet การซื้อ การแลก และ assets'),

  -- Marketing Automation
  ('marketing_automation.workflows.multi_step',
   'Workflow อัตโนมัติหลายขั้น',
   'นักการตลาดสร้าง journey แบบกำหนดไว้ล่วงหน้า ที่ตอบสนองอีเวนต์ลูกค้า รอ แยกทาง ส่งข้อความ และทำ action ฝั่ง loyalty'),
  ('marketing_automation.workflows.audiences',
   'Automation สมาชิกใน Audience',
   'ดูแล audience แบบ dynamic หรือ static แล้วใช้การเข้า/ออกเป็นทริกเกอร์และเป้าของ Workflow'),
  ('marketing_automation.ai_decisioning.agent',
   'AI decisioning agent',
   'ตั้งเป้า action ที่อนุญาต ผลลัพธ์ และข้อจำกัด แล้ว agent เลือกระหว่าง ACT, WAIT หรือ SKIP รายสมาชิก'),
  ('marketing_automation.ai_analysis.recommendations',
   'AI วิเคราะห์และแนะนำ',
   'วิเคราะห์ผล Workflow และ agent แล้วแนะนำว่านักการตลาดควรปรับอะไรต่อ'),

  -- Customer Service
  ('customer_service.connectivity.omnichannel_inbox',
   'Inbox รวม Omnichannel',
   'เอเจนต์ทำงานใน inbox เดียวข้ามช่องทางที่เชื่อมอยู่ พร้อมบันทึกลูกค้าเดียวกัน'),
  ('customer_service.connectivity.channel_connectors',
   'ตัวเชื่อมช่องทาง',
   'เชื่อม marketplace แอปแชท อีเมล เว็บ SMS และช่องทางเกี่ยวข้องเข้าสู่ CS'),
  ('customer_service.connectivity.phone_numbers',
   'จัดการหมายเลขโทรศัพท์',
   'จัดเตรียมและดูแลเบอร์ที่ใช้กับ voice และ SMS ในบริการลูกค้า'),
  ('customer_service.chat_voice.chat',
   'บทสนทนา Chat',
   'รับเรื่องแชทแบบ asynchronous พร้อมประวัติเต็มและเครื่องมือของเอเจนต์'),
  ('customer_service.chat_voice.voice',
   'คอนโซล Voice',
   'รับสายด้วยบริบทลูกค้าชุดเดียวกับที่ใช้กับแชท'),
  ('customer_service.agent_productivity.quick_replies',
   'Quick replies',
   'เอเจนต์แทรกข้อความตอบที่อนุมัติแล้ว เพื่อตอบเร็วและโทนสม่ำเสมอ'),
  ('customer_service.agent_productivity.knowledge_search',
   'ค้นหา Knowledge สำหรับเอเจนต์',
   'เอเจนต์ค้นหา knowledge base ระหว่างคุยกับลูกค้าสด ๆ'),
  ('customer_service.agent_productivity.live_assist',
   'Live assist',
   'ช่วยเอเจนต์ระหว่างสนทนาด้วยข้อความแนะนำและบริบท'),
  ('customer_service.routing_workflows.routing',
   'Routing และการมอบหมาย',
   'ส่งต่อบทสนทนาไปคิว ทักษะ หรือเอเจนต์ตามกฎ'),
  ('customer_service.routing_workflows.chatbot_flows',
   'Chatbot flows',
   'รัน chatbot workflow แบบมองเห็นขั้นตอน ก่อนหรือควบคู่เอเจนต์คน'),
  ('customer_service.analytics.service_analytics',
   'Service analytics',
   'รายงานปริมาณบทสนทนา เวลาตอบ CSAT containment และผลิตภาพเอเจนต์'),
  ('customer_service.ai_agent.brand_ai',
   'AI service agent',
   'AI ที่ตั้งค่าตามแบรนด์ รับหรือช่วยคุยภายใต้กฎโทน ภาษา และการส่งต่อคน'),
  ('customer_service.aop_actions.aops',
   'Agent operating procedures (AOPs)',
   'กำหนดขั้นตอนตาม intent ที่ AI ต้องทำตามเมื่อแก้ปัญหาลูกค้า'),
  ('customer_service.aop_actions.knowledge_base',
   'Knowledge base',
   'เก็บและดึงความรู้บริการ พร้อม citation สำหรับเอเจนต์และ AI'),
  ('customer_service.aop_actions.customer_actions',
   'Customer actions',
   'สั่ง action ที่อนุญาตจาก flow บริการ (ค้นหา ข้อมูล loyalty อินทิเกรชัน)'),
  ('customer_service.supervisor_ai.quality_scoring',
   'คะแนนคุณภาพ (Quality scoring)',
   'ให้คะแนนบทสนทนาของคนและ AI ด้านคุณภาพ การทำตามนโยบาย และสัญญาณสำหรับโค้ช'),
  ('customer_service.supervisor_ai.watchtower',
   'Supervisor AI / Watchtower',
   'รีวิวโดย supervisor ที่ตรวจเคส AI และคน แล้วป้อนกลับเพื่อปรับ prompt/AOP')
),
upd AS (
  UPDATE internal_product_feature f
  SET
    name_th = th.name_th,
    summary_th = th.summary_th,
    updated_at = now()
  FROM th
  WHERE f.feature_key = th.feature_key
  RETURNING f.feature_key, f.name, f.name_th, f.summary, f.summary_th
)
INSERT INTO internal_product_catalog_change_log (
  run_id, entity_type, entity_key, change_type,
  before_snapshot, after_snapshot, source_refs
)
SELECT
  'b7e4a91c-2d8f-4c3a-a1e0-202608120001'::uuid,
  'feature',
  u.feature_key,
  'update',
  jsonb_build_object('name_th', null, 'summary_th', null),
  jsonb_build_object('name_th', u.name_th, 'summary_th', u.summary_th),
  '[{"kind":"plan","path":"workflows/product-feature-catalog/REFERENCE.md","heading":"6.1 Thai localization"},{"kind":"writing","path":"Writing Principles/TRANSLATION_PHILOSOPHY.md"},{"kind":"writing","path":"Writing Principles/TRANSLATION_PRINCIPLES.md"}]'::jsonb
FROM upd u;

COMMIT;

-- Verification
SELECT count(*) FILTER (WHERE name_th IS NOT NULL AND summary_th IS NOT NULL) AS localized,
       count(*) FILTER (WHERE name_th IS NULL OR summary_th IS NULL) AS missing_th,
       count(*) AS total
FROM internal_product_feature
WHERE is_active;
