-- Generated by scripts/gen_phase2.py — fix_thai_address_master_phase2
-- Sources: DOPA ccaatt (1 Sep 2023); Thailand Post postcode poster (2018)

-- Backup (RLS enabled, no policies)
CREATE TABLE public._bak_20261002_p2_address_th_subdistrict AS
SELECT * FROM public.address_th_subdistrict WHERE id IN ('110401', '110402', '110602', '110603', '140121', '140411', '141108', '141109', '150410', '150601', '160107', '160509', '190603', '200109', '200409', '200604', '210110', '221001', '240114', '240409', '260403', '310106', '310610', '311006', '320516', '331405', '342504', '380103', '410111', '410116', '430111', '441106', '451014', '460708', '461603', '461703', '461803', '461804', '461805', '481202', '481203', '500108', '500109', '502502', '520205', '520904', '530405', '540103', '540113', '550107', '550116', '550510', '551003', '551502', '560108', '601303', '630206', '660104', '730120', '730312', '760102', '801216', '801406', '830104', '830105', '900703', '901604', '910303', '920106', '920221', '920222', '920305', '920414', '940701', '940804', '960507', '961001', '961002');
ALTER TABLE public._bak_20261002_p2_address_th_subdistrict ENABLE ROW LEVEL SECURITY;
CREATE TABLE public._bak_20261002_p2_address_th_district AS
SELECT * FROM public.address_th_district WHERE id IN ('3801', '4906', '9310', '9508');
ALTER TABLE public._bak_20261002_p2_address_th_district ENABLE ROW LEVEL SECURITY;
CREATE TABLE public._bak_20261002_p2_user_address AS
SELECT id, province_code, district_code, subdistrict_code, city, district, subdistrict
FROM public.user_address
WHERE subdistrict_code IN ('110401', '110402', '110602', '110603', '140121', '140411', '141108', '141109', '150410', '150601', '160107', '160509', '190603', '200109', '200409', '200604', '210110', '221001', '240114', '240409', '260403', '310106', '310610', '311006', '320516', '331405', '342504', '380103', '410111', '410116', '430111', '441106', '451014', '460708', '461603', '461703', '461803', '461804', '461805', '481202', '481203', '500108', '500109', '502502', '520205', '520904', '530405', '540103', '540113', '550107', '550116', '550510', '551003', '551502', '560108', '601303', '630206', '660104', '730120', '730312', '760102', '801216', '801406', '830104', '830105', '900703', '901604', '910303', '920106', '920221', '920222', '920305', '920414', '940701', '940804', '960507', '961001', '961002')
   OR district_code IN ('3801', '4906', '9310', '9508');
ALTER TABLE public._bak_20261002_p2_user_address ENABLE ROW LEVEL SECURITY;

-- Step 1: insert 3 subdistricts that DOPA lists and we lack
INSERT INTO public.address_th_subdistrict (id, zip_code, subdistrict_name_th, subdistrict_name_en, district_id, district_name_th, district_name_en)
SELECT v.id, v.zip_code, v.name_th, v.name_en, d.id::bigint, d.district_name_th, d.district_name_en
FROM (VALUES
  ('410116', 41000, 'ต.นาข่า', 'Na Kha', '4101'),
  ('500108', 50200, 'ต.สุเทพ', 'Suthep', '5001'),
  ('830104', 83000, 'ต.รัษฎา', 'Ratsada', '8301')
) AS v(id, zip_code, name_th, name_en, district_code)
JOIN public.address_th_district AS d ON d.id = v.district_code;

-- Step 2: re-point saved addresses to the code that officially holds the name the member picked
UPDATE public.user_address AS ua
SET subdistrict_code = m.new_code,
    subdistrict = CASE WHEN ua.subdistrict = m.old_code THEN m.new_code ELSE ua.subdistrict END
FROM (VALUES
  ('110402', '110401'),
  ('141108', '141109'),
  ('141109', '141108'),
  ('410111', '410116'),
  ('461803', '461804'),
  ('461804', '461805'),
  ('461805', '461803'),
  ('481202', '481203'),
  ('481203', '481202'),
  ('500109', '500108')
) AS m(old_code, new_code)
WHERE ua.subdistrict_code = m.old_code;

-- Step 3: correct 67 subdistrict names to DOPA
CREATE TEMP TABLE _p2_sub_rename (id text PRIMARY KEY, old_th text, new_th text, new_en text) ON COMMIT DROP;
INSERT INTO _p2_sub_rename VALUES
  ('110401', 'ต.เทศบาลเมืองพระประแดง', 'ต.ตลาด', 'Talat'),
  ('110402', 'ต.ตลาด', 'ต.บางพึ่ง', 'Bang Phueng'),
  ('110602', 'ต.ศรีษะจรเข้น้อย', 'ต.ศีรษะจรเข้น้อย', 'Sisa Chorakhe Noi'),
  ('110603', 'ต.ศรีษะจรเข้ใหญ่', 'ต.ศีรษะจรเข้ใหญ่', 'Sisa Chorakhe Yai'),
  ('140121', 'ต.บ้านรุม', 'ต.บ้านรุน', 'Ban Run'),
  ('140411', 'ต.บ้างกลึง', 'ต.บ้านกลึง', 'Ban Klueng'),
  ('141108', 'ต.ข้าวงาม', 'ต.วังจุฬา', 'Wang Chula'),
  ('141109', 'ต.วังจุฬา', 'ต.ข้าวงาม', 'Khao Ngam'),
  ('150410', 'ต.ยางซ้าย', 'ต.ยางช้าย', 'Yang Chai'),
  ('150601', 'ต.ไผ่จำศีล', 'ต.ไผ่จำศิล', 'Phai Chamsin'),
  ('160107', 'ต.โคกกระเทียม', 'ต.โคกกะเทียม', 'Khok Kathiam'),
  ('160509', 'ต.ลาดสาลี', 'ต.ลาดสาลี่', 'Lat Sali'),
  ('190603', 'ต.สร้างโศก', 'ต.สร่างโศก', 'Sang Sok'),
  ('200109', 'ต.ดอนหัวฬอ', 'ต.ดอนหัวฬ่อ', 'Don Hua Lo'),
  ('200604', 'ต.บ้านเชิด', 'ต.บ้านเซิด', 'Ban Soet'),
  ('210110', 'ต.กระเฉด', 'ต.กะเฉด', 'Kachet'),
  ('221001', 'ต.ซากไทย', 'ต.ชากไทย', 'Chak Thai'),
  ('240114', 'ต.บางกระไห', 'ต.บางกะไห', 'Bang Kahai'),
  ('260403', 'ต.ศรีษะกระบือ', 'ต.ศีรษะกระบือ', 'Sisa Krabue'),
  ('310106', 'ต.สวายจึก', 'ต.สวายจีก', 'Sawai Chik'),
  ('310610', 'ต.หนองตระครอง', 'ต.หนองตะครอง', 'Nong Takhrong'),
  ('311006', 'ต.หนองกระทิง', 'ต.หนองกะทิง', 'Nong Kathing'),
  ('320516', 'ต.กันตรวจระมวล', 'ต.กันตวจระมวล', 'Kantuat Ramuan'),
  ('331405', 'ต.เสืองข้าว', 'ต.เสื่องข้าว', 'Sueang Khao'),
  ('342504', 'ต.นิคมลำโดมน้อย', 'ต.นิคมสร้างตนเองลำโดมน้อย', 'Nikhom Sang Ton-eng Lam Dom Noi'),
  ('380103', 'ต.หนองเข็ง', 'ต.โนนสว่าง', 'Non Sawang'),
  ('410111', 'ต.นาข่า', 'ต.นาดี', 'Na Di'),
  ('430111', 'ต.สองห้อง', 'ต.โพนสว่าง', 'Phon Sawang'),
  ('441106', 'ต.ขามเรียน', 'ต.สร้างแซ่ง', 'Sangsaeng'),
  ('451014', 'ต.ศรีวิสัย', 'ต.ศรีวิลัย', 'Si Wilai'),
  ('460708', 'ต.หนองอีเฒ่า', 'ต.หนองอิเฒ่า', 'Nong I Thao'),
  ('461603', 'ต.โนนนาจาง', 'ต.โนนนาจาน', 'Non Na Chan'),
  ('461703', 'ต.พยุง', 'ต.ดงพยุง', 'Dong Phayung'),
  ('461803', 'ต.โนนศิลา', 'ต.โคกสะอาด', 'Khok Sa-at'),
  ('461804', 'ต.ลำชี', 'ต.โนนศิลาเลิง', 'Non Sila Loeng'),
  ('461805', 'ต.โคกสะอาด', 'ต.ลำชี', 'Lam Chi'),
  ('481202', 'ต.ยอดชาด', 'ต.โคกสี', 'Khok Si'),
  ('481203', 'ต.โคกสี', 'ต.ยอดชาด', 'Yot Chat'),
  ('500109', 'ต.สุเทพ', 'ต.แม่เหียะ', 'Mae Hia'),
  ('502502', 'ต.แม่แดด', 'ต.แม่แดด', 'Mae Daet'),
  ('520205', 'ต.สบป้าน', 'ต.สบป้าด', 'Sop Pat'),
  ('520904', 'ต.พระบาทวังตวง', 'ต.พระบาทวังตวง', 'Phra Bat Wang Tuang'),
  ('530405', 'ต.น้ำไฝ', 'ต.น้ำไผ่', 'Nam Phai'),
  ('540103', 'ต.นาชำ', 'ต.น้ำชำ', 'Nam Cham'),
  ('540113', 'ต.วังหงษ์', 'ต.วังหงส์', 'Wang Hong'),
  ('550107', 'ต.นาชาว', 'ต.นาซาว', 'Na Sao'),
  ('550116', 'ต.สวก', 'ต.บ่อสวก', 'Bo Suak'),
  ('550510', 'ต.เจดียชัย', 'ต.เจดีย์ชัย', 'Chedi Chai'),
  ('551003', 'ต.เมืองลี่', 'ต.เมืองลี', 'Mueang Li'),
  ('560108', 'ต.แม่ปีม', 'ต.แม่ปืม', 'Mae Puem'),
  ('601303', 'ต.แม่เลย์', 'ต.แม่เล่ย์', 'Mae Le'),
  ('630206', 'ต.ทุ่งกระเซาะ', 'ต.ทุ่งกระเชาะ', 'Thung Kracho'),
  ('660104', 'ต.ท่าฬอ', 'ต.ท่าฬ่อ', 'Tha Lo'),
  ('730120', 'ต.สระกระเทียม', 'ต.สระกะเทียม', 'Sa Kathiam'),
  ('730312', 'ต.ศีรษะทอง', 'ต.ศรีษะทอง', 'Sisa Thong'),
  ('760102', 'ต.คลองกระแซง', 'ต.คลองกระแชง', 'Khlong Krachaeng'),
  ('801216', 'ต.ท่าพญา', 'ต.ท่าพยา', 'Tha Phaya'),
  ('801406', 'ต.สีขีด', 'ต.สี่ขีด', 'Si Khit'),
  ('830105', 'ต.รัษฎา', 'ต.วิชิต', 'Wichit'),
  ('900703', 'ต.ตาเครียะ', 'ต.ตะเครียะ', 'Takhria'),
  ('910303', 'ต.อุไดเจริญ', 'ต.อุใดเจริญ', 'Udai Charoen'),
  ('920305', 'ต.โพรงจรเข้', 'ต.โพรงจระเข้', 'Phrong Chorakhe'),
  ('940701', 'ต.ตะลุปัน', 'ต.ตะลุบัน', 'Talu Ban'),
  ('940804', 'ต.คอนทราย', 'ต.ดอนทราย', 'Don Sai'),
  ('960507', 'ต.กาลิชา', 'ต.กาลิซา', 'Kalisa'),
  ('961001', 'ต.สุไหงโกลก', 'ต.สุไหงโก-ลก', 'Su-ngai Kolok'),
  ('961002', 'ต.ป่าเสมัส', 'ต.ปาเสมัส', 'Pa Semat')
;
UPDATE public.address_th_subdistrict AS s
SET subdistrict_name_th = r.new_th, subdistrict_name_en = r.new_en
FROM _p2_sub_rename AS r WHERE s.id = r.id;
UPDATE public.user_address AS ua
SET subdistrict = r.new_th
FROM _p2_sub_rename AS r
WHERE ua.subdistrict_code = r.id AND ua.subdistrict = r.old_th AND r.old_th <> r.new_th;

-- Step 4: 4 postcodes where Thailand Post agrees with the reference
UPDATE public.address_th_subdistrict SET zip_code = 24130 WHERE id = '240409';
UPDATE public.address_th_subdistrict SET zip_code = 55130 WHERE id = '551502';
UPDATE public.address_th_subdistrict SET zip_code = 90115 WHERE id = '901604';
UPDATE public.address_th_subdistrict SET zip_code = 92000 WHERE id = '920106';

-- Step 5: correct 4 district names to DOPA and refresh child rows
UPDATE public.address_th_district SET district_name_th = 'อ.เมืองบึงกาฬ', district_name_en = 'Mueang Bueng Kan' WHERE id = '3801';
UPDATE public.user_address SET district = 'อ.เมืองบึงกาฬ' WHERE district_code = '3801' AND district = 'อ.บึงกาฬ';
UPDATE public.address_th_district SET district_name_th = 'อ.หว้านใหญ่', district_name_en = 'Wan Yai' WHERE id = '4906';
UPDATE public.user_address SET district = 'อ.หว้านใหญ่' WHERE district_code = '4906' AND district = 'อ.ว่านใหญ่';
UPDATE public.address_th_district SET district_name_th = 'อ.ป่าพะยอม', district_name_en = 'Pa Phayom' WHERE id = '9310';
UPDATE public.user_address SET district = 'อ.ป่าพะยอม' WHERE district_code = '9310' AND district = 'อ.ป่าพยอม';
UPDATE public.address_th_district SET district_name_th = 'อ.กรงปินัง', district_name_en = 'Krong Pinang' WHERE id = '9508';
UPDATE public.user_address SET district = 'อ.กรงปินัง' WHERE district_code = '9508' AND district = 'อ.กรงปีนัง';
UPDATE public.address_th_subdistrict AS s
SET district_name_th = d.district_name_th, district_name_en = d.district_name_en
FROM public.address_th_district AS d
WHERE s.district_id = d.id::bigint AND d.id IN ('3801', '4906', '9310', '9508');

-- Step 6: delete 4 codes DOPA does not list (abort if any saved address uses them)
DO $$
DECLARE n int;
BEGIN
  SELECT count(*) INTO n FROM public.user_address WHERE subdistrict_code IN ('200409', '920221', '920222', '920414');
  IF n > 0 THEN RAISE EXCEPTION 'user_address still references deleted codes: %', n; END IF;
END $$;
DELETE FROM public.address_th_subdistrict WHERE id IN ('200409', '920221', '920222', '920414');

-- Step 7: subdistrict codes must now equal DOPA's active list exactly
DO $$
DECLARE n int; h text;
BEGIN
  SELECT count(*), md5(string_agg(id, ',' ORDER BY id)) INTO n, h FROM public.address_th_subdistrict;
  IF n <> 7436 OR h <> '18892d7089a8755886b5b94a1a655cb9' THEN
    RAISE EXCEPTION 'subdistrict codes differ from DOPA: count % (expected 7436), md5 %', n, h;
  END IF;
END $$;
